$onEmpty
 b1.M  = Eps ;
 b2.M  = Eps ;
 b3.L  = 1 ;
 b4.L  = 1 ;
 b4.M  = Eps ;
 b5.L  = 1 ;
$offListing
 b5.M  = Eps ;
 b6.L  = 1 ;
 b6.M  = -12 ;
 b7.L  = 1 ;
 b7.M  = -12 ;
 b8.L  = 1 ;
 b8.M  = Eps ;
 b9.M  = 4 ;
 b10.L  = 1 ;
 b10.M  = Eps ;
 b11.L  = 1 ;
 b11.M  = 12 ;
 b12.M  = 8 ;
 b13.M  = Eps ;
 b14.L  = 1 ;
 b14.M  = Eps ;
 b15.M  = -21 ;
 b16.L  = 1 ;
 b16.M  = Eps ;
 objvar.L  = 13 ;
 e1.M  = 1 ;
 ;
 ;
 e4.M  = -13 ;
 ;
 ;
 ;
 ;

$offEmpty
$onListing
