set a authors /
"Adjiman, C S"
"Aiyoshi, E"
"Al-Mahaidi, R"
"Anandalingam, G"
"Bard, J F"
"Bixby, R"
"Candler, W"
"Carolan, W J"
"Ceria, S"
"Clark, P A"
"DeSilva, A H"
"Dirkse, S P"
"Esposito, W R"
"Facchinei, F"
"Falk, J E"
"Ferris, M C"
"Floudas, C A"
"Fukushima, M"
"Gauvin, J"
"Giannessi, F"
"Grzebieta, R H"
"Gumus, Z H"
"Handbook of Test Problems"
"Hansen"
"Harding, S T"
"Hart, S M"
"Hearn"
"Henderson, J M"
"Hill, J E"
"Ishizuka, Y"
"Jaumard"
"Jiang, H"
"Kehoe, T"
"Kennington J L"
"Klepeis, J L"
"Kocvara"
"Light, M"
"Liu, J"
"Liu, Y H"
"Luo, Z"
"Maier, G"
"McZeal C M"
"Meyer, C A"
"Murphy, F H"
"Nappi, A"
"Nemhauser, G L"
"Niemi, S"
"Outrata, J V"
"Pang, J S"
"Pardalos, P M"
"Qi, L"
"Quandt, R E"
"Ralph, D"
"Ramana"
"Savard, G"
"Savelsbergh, M W P"
"Scholtes, S"
"Schweiger, C A"
"Sherali, H D"
"Shimizu, K"
"Soyster, A L"
"Stohr, M"
"Tin-Loi, F"
"Toint, P L"
"Townsley, R"
"Trick, M A"
"Visweswaran, V"
"Westerberg, A W"
"White, D J"
"Wichmann, S J"
"Wilson, J L"
"Yezza, A"
"Zowe, J"
/
set r references /
r1  "Bard, J F, Convex Two-Level Optimization. Mathematical Programming 40 (1988), 15-27."
r2  "DeSilva, A H, Sensitivity Formulas for Nonlinear Factorable Programming and their Application to the Solution of an Implicitly Defined Optimization Model of US Crude Oil Production. PhD thesis, George Washington University, 1978."
r3  "Facchinei, F, Jiang, H, and Qi, L, A Smoothing Method for Mathematical Programs with Equilibrium Constraints. Tech. rep., Universita di Roma La Sapienza, 1996."
r4  "Henderson, J M, and Quandt, R E, Microeconomic Theory. McGraw Hill, New York, 1980. 3rd edition"
r5  "Murphy, F H, Sherali, H D, and Soyster, A L, A Mathematical Programming Approach for Determining Oligopolistic Market Equilibrium. Mathematical Programming 24 (1982), 92-106."
r6  "Outrata, J V, and Zowe, J, A Numerical Approach to Optimization Problems with Variational Inequality Constraints. Mathematical Programming 68 (1995), 105-130."
r7  "Dirkse, S P, and Ferris, M C, MCPLIB: A Collection of Nonlinear Mixed Complementarity Problems. Optimization Methods and Software 5 (1995), 319-345."
r8  "Toint, P L, Ed, Operations Research and Decision Aid Methodologies in Traffic and Transportation Management. Springer Verlag, 1997. NATO ASI Series F"
r9  "Dirkse, S P, and Ferris, M C, Traffic Modeling and Variational Inequalities Using GAMS. In Toint, P L, Ed, Operations Research and Decision Aid Methodologies in Traffic and Transportation Management. Springer Verlag, 1997."
r10  "Savard, G, and Gauvin, J, The Steepest Descent for the Nonlinear Bilevel Programming Problem. Operation Research Letters 15 (1994), 265-272."
r11  "Fukushima, M, and Qi, L, Eds, Reformulation: Nonsmooth, Piecewise Smooth, Semismooth and Smoothing Methods. Kluwer Academic Publishers, 1999."
r12  "Dirkse, S P, and Ferris, M C, Modeling and Solution Environments for MPEC: GAMS and MATLAB. In Fukushima, M, and Qi, L, Eds, Reformulation: Nonsmooth, Piecewise Smooth, Semismooth and Smoothing Methods. Kluwer Academic Publishers, 1999, pp. 127-148."
r13  "Grzebieta, R H, Al-Mahaidi, R, and Wilson, J L, Eds, Proceedings of 15th ACMSM, 1997."
r14  "Maier, G, Giannessi, F, and Nappi, A, Indirect Identification of Yield Limits by Mathematical Programming. Engineering Structures 4 (1982), 86-98."
r15  "Jiang, H, Ralph, D, and Tin-Loi, F, Identification of Yield Limits .... In Grzebieta, R H, Al-Mahaidi, R, and Wilson, J L, Eds, Proceedings of 15th ACMSM. Balkema, Rotterdam, Melbourne, Australia, 1997, pp. 399-404."
r16  "Ferris, M C, and Tin-Loi, F, On the Solution of a Minimum Weight Elastoplastic Problem Involving Displacement and Complementarity Constraints. Comp. Meth. in Appl. Mech. and Engng 174 (1999), 107-120."
r17  "Outrata, J V, On Optimization Problems with Variational Inequality Constraints. SIAM J. Optim. 4 (1994), 340-357."
r18  "Scholtes, S, and Stohr, M, Exact Penalization of Mathematical Programs with Equilibrium Constraints. SIAM J. Control Optim. 37, 2 (1999), 617-652."
r19  "Ferris, M C, and Tin-Loi, F, Nonlinear Programming Approach for a Class of Inverse Problems in Elastoplasticity. Structural Engineering and Mechanics 6 (1998), 857-870."
r20  "Luo, Z, Pang, J S, and Ralph, D, Mathematical Programs with Equilibrium Constraints. CUP, 1997."
r21  "Floudas, C A, Pardalos, P M, Adjiman, C S, Esposito, W R, Gumus, Z H, Harding, S T, Klepeis, J L, Meyer, C A, and Schweiger, C A, Handbook of Test Problems in Local and Global Optimization. Kluwer Academic Publishers, 1999."
r22  "Yezza, A, First-Order Necessary Optimality Conditions for General Bilevel Programming Problems. Journal of Optimization Theory and Applications 89 (1996), 189-219."
r23  "Clark, P A, and Westerberg, A W, Bilevel Programming for Steady-State Chemical Process Design-i. Fundamentals and Algorithms. Comput. Chem. Eng. 14 (1990), 87."
r24  "Liu, Y H, and Hart, S M, Characterizing an Optimal Solution to the Linear Bilevel Programming Problem. European Journal of Operational Research 79 (1994), 164-166."
r25  "Clark, P A, and Westerberg, A W, A Note on the Optimality Conditions for the Bilevel Programming Problem. Naval Research Logistics 35 (1988), 413-418."
r26  "Shimizu, K, and Aiyoshi, E, A New Computational Method for Stackelberg and Mim-Max Problems by Use of a Penalty Method. IEEE Trans. on Aut. Control 26 (1981)."
r27  "Visweswaran, V, A Decomposition-Based Global Optimization Approach for Solving Bilevel Linear and Quadratic Programs. In Floudas, C A, and Pardalos, P M, Eds, State of the Art in Global Optimization. Kluwer Academic Publishers, 1996, p. 139."
r28  "Bard, J F, Some Properties of the Bilevel Programming Problem. Journal of Optimization Theory and Applications 68 (1991), 371-378."
r29  "Bard, J F, and Falk, J E, An Explicit Solution to the Multi-Level Programming Problem. Comp. Op. Res. 9 (1982), 77-100."
r30  "Falk, J E, and Liu, J, On Bilevel Programming, Part i: General Nonlinear Cases. Mathematical Programming 70 (1995), 47."
r31  "Shimizu, K, Ishizuka, Y, and Bard, J F, Nondifferentiable and Two-Level Mathematical Programming. Kluwer Academic Publishers, 1997."
r32  "Floudas, C A, and Pardalos, P M, Eds, State of the Art in Global Optimization. Kluwer Academic Publishers, 1996."
r33  "Candler, W, and Townsley, R, A Linear Two-Level Programming Problem. Comp. Op. Res. 9 (1982), 59-76."
r34  "Anandalingam, G, and White, D J, A Solution Method for the Linear Static Stackelberg Problem Using Penalty Functions. IEEE Trans. Auto. Contr. 35 (1990), 1170-1173."
r35  "Hansen, Jaumard, and Savard, G, New Branch-and-Bound Rules for Linear Bilevel Programming. SIAM J. Sci. Stat. Comp 13 (1992), 1194-1217."
r36  "Light, M, Optimal Taxation: An Application of Mathematical Programming with Equilibrium Constraints in Economics. Tech. rep., Department of Economics, University of Colorado, Boulder, 1999."
r37  "Outrata, J V, Kocvara, and Zowe, J, Nonsmooth Approach to Optimization Problems with Equilibrium Constraints. Kluwer, 1998."
r38  "Jiang, H, and Ralph, D, Smooth SQP Methods for Mathematical Programs with Nonlinear Complementarity Constraints. Tech. rep., University of Melbourne, 1997."
r39  "Jiang, H, and Ralph, D, QPECgen: A MATLAB Generator for Mathematical Programs with Quadratic Objectives and Affine Variational Inequality Cnostraints. Computational Optimization and Applications (0000)."
r40  "Scholtes, S, Research Papers in Managements Studies. Tech. rep., The Judge Institute, University of Cambridge, 1997."
r41  "Hearn, and Ramana, Solving Congestion Toll Pricing Models. Tech. rep., University of Florida, 0000."
r42  "Bixby, R, Ceria, S, McZeal C M, and Savelsbergh, M W P, An Updated Mixed Integer Programming Library: MIPLIB 3.0. Optima 58 (1998), 12-15."
r43  "Carolan, W J, Hill, J E, Kennington J L, Niemi, S, and Wichmann, S J, An Empirical Evaluation of the KORBX Algorithms for Military Airlift Applications. Operations Research 38, 2 (1990), 240-248."
r44  "Nemhauser, G L, and Trick, M A, Scheduling a Major College Basketball Conference. Operations Research 46 (1998), 1-8."
r45  "Kehoe, T, A Numerical Investigation of the Multiplicity of Equilibria. Mathematical Programming Study 23 (1985), 240-258."
r46  "Pang, J S, and Tin-Loi, F, A penalty interior point algorithm for a inverse parameter identification problem in elastoplasticity. Mechanics of Structures and Machines 29 (2001), 85-99."
/
$onempty
set cr(r,r) cross references /
r8.(r9)
r11.(r12)
r13.(r15)
r32.(r27)
/
$offempty
$onempty
set ca(a) credit authors /
"Handbook of Test Problems"
/
$offempty
set af(a,r) first author     /
"Anandalingam, G".(r34)
"Bard, J F".(r28,r29,r1)
"Bixby, R".(r42)
"Candler, W".(r33)
"Carolan, W J".(r43)
"Clark, P A".(r23,r25)
"DeSilva, A H".(r2)
"Dirkse, S P".(r7,r9,r12)
"Facchinei, F".(r3)
"Falk, J E".(r30)
"Ferris, M C".(r16,r19)
"Floudas, C A".(r21,r32)
"Fukushima, M".(r11)
"Grzebieta, R H".(r13)
"Hansen".(r35)
"Hearn".(r41)
"Henderson, J M".(r4)
"Jiang, H".(r15,r38,r39)
"Kehoe, T".(r45)
"Light, M".(r36)
"Liu, Y H".(r24)
"Luo, Z".(r20)
"Maier, G".(r14)
"Murphy, F H".(r5)
"Nemhauser, G L".(r44)
"Outrata, J V".(r6,r37,r17)
"Pang, J S".(r46)
"Savard, G".(r10)
"Scholtes, S".(r18,r40)
"Shimizu, K".(r26,r31)
"Toint, P L".(r8)
"Visweswaran, V".(r27)
"Yezza, A".(r22)
/
set ar(a,r) author reference mapping /
"Adjiman, C S".(r21)
"Aiyoshi, E".(r26)
"Al-Mahaidi, R".(r13)
"Anandalingam, G".(r34)
"Bard, J F".(r28,r29,r31,r1)
"Bixby, R".(r42)
"Candler, W".(r33)
"Carolan, W J".(r43)
"Ceria, S".(r42)
"Clark, P A".(r23,r25)
"DeSilva, A H".(r2)
"Dirkse, S P".(r7,r9,r12)
"Esposito, W R".(r21)
"Facchinei, F".(r3)
"Falk, J E".(r29,r30)
"Ferris, M C".(r7,r9,r12,r16,r19)
"Floudas, C A".(r21,r32)
"Fukushima, M".(r11)
"Gauvin, J".(r10)
"Giannessi, F".(r14)
"Grzebieta, R H".(r13)
"Gumus, Z H".(r21)
"Handbook of Test Problems".(r21)
"Hansen".(r35)
"Harding, S T".(r21)
"Hart, S M".(r24)
"Hearn".(r41)
"Henderson, J M".(r4)
"Hill, J E".(r43)
"Ishizuka, Y".(r31)
"Jaumard".(r35)
"Jiang, H".(r3,r15,r38,r39)
"Kehoe, T".(r45)
"Kennington J L".(r43)
"Klepeis, J L".(r21)
"Kocvara".(r37)
"Light, M".(r36)
"Liu, J".(r30)
"Liu, Y H".(r24)
"Luo, Z".(r20)
"Maier, G".(r14)
"McZeal C M".(r42)
"Meyer, C A".(r21)
"Murphy, F H".(r5)
"Nappi, A".(r14)
"Nemhauser, G L".(r44)
"Niemi, S".(r43)
"Outrata, J V".(r6,r37,r17)
"Pang, J S".(r20,r46)
"Pardalos, P M".(r21,r32)
"Qi, L".(r3,r11)
"Quandt, R E".(r4)
"Ralph, D".(r20,r15,r38,r39)
"Ramana".(r41)
"Savard, G".(r10,r35)
"Savelsbergh, M W P".(r42)
"Scholtes, S".(r18,r40)
"Schweiger, C A".(r21)
"Sherali, H D".(r5)
"Shimizu, K".(r26,r31)
"Soyster, A L".(r5)
"Stohr, M".(r18)
"Tin-Loi, F".(r16,r15,r19,r46)
"Toint, P L".(r8)
"Townsley, R".(r33)
"Trick, M A".(r44)
"Visweswaran, V".(r27)
"Westerberg, A W".(r23,r25)
"White, D J".(r34)
"Wichmann, S J".(r43)
"Wilson, J L".(r13)
"Yezza, A".(r22)
"Zowe, J".(r6,r37)
/
