$onEmpty
 b1.L  = 1 ;
 b1.M  = 0.1 ;
 b2.L  = 1 ;
 b2.M  = 0.2 ;
 b3.M  = -35.7 ;
 b4.M  = -35.6 ;
$offListing
 i5.L  = 4 ;
 i6.L  = 4 ;
 ;
 ;
 i9.L  = 1 ;
 i10.L  = 1 ;
 i11.L  = 4 ;
 i12.L  = 4 ;
 i13.M  = Eps ;
 i14.L  = 2 ;
 i15.M  = Eps ;
 i16.M  = Eps ;
 i17.L  = 3 ;
 i18.M  = 4 ;
 i19.M  = Eps ;
 i20.L  = 1 ;
 i21.L  = 1 ;
 i22.L  = 2 ;
 i23.L  = 1 ;
 i24.M  = Eps ;
 objvar.L  = 8.3 ;
 e1.M  = 1 ;
 e2.M  = Eps ;
 ;
 ;
 ;
 ;
 ;
 ;
 e9.M  = Eps ;
 ;
 e11.M  = -4 ;
 e12.M  = Eps ;
 ;
 ;
 ;
 ;
 ;
 ;
 ;
 e20.M  = -3 ;
 e21.M  = -3 ;
 e22.M  = -1 ;
 ;
 e24.M  = Eps ;
 ;

$offEmpty
$onListing
