set a authors /
"Andrew Boyd, E"
"Aronson, J E"
"Barutt, J"
"Bienstock, D"
"Binous, H"
"Bixby, R"
"Bouvier, B"
"Carolan, W J"
"Ceria, S"
"Cook, W"
"Crowder, H"
"Drinka, D"
"Eckstein, J"
"Edgar, T F"
"Gailly, B"
"GAMS Dev. Client Models"
"GAMS Development"
"Gottlieb, J"
"Hill, J E"
"Himmelblau, D M"
"Hoffman, K L"
"Hull, T"
"Johnson, E L"
"Kennington J L"
"Lasdon, L S"
"Lemke, C"
"McKeown, P G"
"McZeal C M"
"Messoumian, G"
"MIPLIB 3.0 Library"
"Miscellaneous LP Models"
"Mittelmann H. - LP Models"
"Mittelmann H. - MIP Models"
"Mittelmann, H"
"MOSEK ApS"
"Nemhauser, G L"
"NEOS MIP Benchmark"
"NETLIB Infeasible LP Library"
"NETLIB LP Repository"
"Niemi, S"
"Padberg, M"
"Paulmann, L"
"Problematic LP Models"
"Rutherford, T"
"Sallcoss, D"
"Savelsbergh, M W P"
"Scarf, H E"
"Senju, S"
"Spielberg, K"
"Stochastic LP Models"
"Suhl, U H"
"Sun, M"
"Toyoda, Y"
"Trick, M A"
"Van Roy, T J"
"Wichmann, S J"
"Wolsey, L A"
/
set r references /
r1  "Bixby, R, Ceria, S, McZeal C M, and Savelsbergh, M W P, An Updated Mixed Integer Programming Library: MIPLIB 3.0. Optima 58 (1998), 12-15."
r2  "Carolan, W J, Hill, J E, Kennington J L, Niemi, S, and Wichmann, S J, An Empirical Evaluation of the KORBX Algorithms for Military Airlift Applications. Operations Research 38, 2 (1990), 240-248."
r3  "Nemhauser, G L, and Trick, M A, Scheduling a Major College Basketball Conference. Operations Research 46 (1998), 1-8."
r4  "Barutt, J, and Hull, T, Airline Crew Scheduling: Supercomputers and Algorithms. SIAM News 23, 6 (1990)."
r5  "Cook, W, Rutherford, T, Scarf, H E, and Sallcoss, D, An Implementation of the Generalized Basis Reduction Algorithme for Integer Programming. Tech. rep., DIMACS, 1980."
r6  "Gailly, B, and Wolsey, L A, Capacity Expansion of the Local Access Network."
r7  "Bienstock, D, Computational Experience with an Effective Heuristic for Some Capacity Expansion Problems in the Local Access Networks."
r8  "Cook, W, Integer Programming Solutions for Capacity Expansion of the Local Access Network. Tech. rep., Bellcore Technical Memorandum, 1991."
r9  "Bouvier, B, and Messoumian, G, Programmes Lineaires en Variables Bivalentes--Algorithm de Balas. Tech. rep., Universite de Grenoble, 1965."
r10  "Johnson, E L, and Suhl, U H, Experiments in Integer Programming. Discrete Appl. Math. 2 (1980), 39-55."
r11  ", Proceedings of Supercomputing '94, 1994."
r12  "Eckstein, J, Control Strategies for Parallel Mixed Integer Branch and Bound. In Proceedings of Supercomputing '94. IEEE Computer Society Press, Los Alamitos, CA, 1994, pp. 41-48."
r13  "Eckstein, J, Parallel Branch-and-Bound Methods for Mixed-Integer Programming on the CM-5. SIAM Journal on Optimization 4, 4 (1994), 794-814."
r14  "Van Roy, T J, and Wolsey, L A, Solving Mixed Integer Programming Problems Using Automatic Reformulation. Oper. Res. 35, 1 (1987), 45-47."
r15  "Lemke, C, and Spielberg, K, Direct Search Zero-One nd Mixed Integer Programming. Oper. Res. 15 (1967), 892-914."
r16  "Hoffman, K L, and Padberg, M, Improving LP-Representations of Zero-One Linear Programs for Branch-and-Cut. ORSA Journal on Computing 3, 2 (1991)."
r17  "Crowder, H, Johnson, E L, and Padberg, M, Solving Large-Scale Zero-One Linear Programming Problems. Operations Research 31, 5 (1983)."
r18  "Andrew Boyd, E, Fenchel Cutting Planes for Integer Programs. to appear in Operations Research"
r19  "Andrew Boyd, E, Generating Fenchel Cutting Planes for Knapsack Polyhedra. to appear in the SIAM Journal on Optimization"
r20  "Andrew Boyd, E, Solving Integer Programs with Enumeration Cutting Planes."
r21  "Eckstein, J, Parallel Branch-and-Bound Methods for Mixed Integer Programming. SIAM News 27, 1 (1994), 1-1215."
r22  "Senju, S, and Toyoda, Y, An Approach to Linear Programming wht 0-1 Variables. Management Science 15 (1968), b196-b207."
r23  "NETLIB LP Repository, online at http://www.netlib.org/lp/data."
r24  "NEOS MIP Benchmark, online at ftp://ftp.mcs.anl.gov/neos/mip-bench/."
r25  "Gottlieb, J, and Paulmann, L, Genetic Algorithms for the Fixed Charge Transportation Problem. Proceedings of the 5th IEEE International Conference on Evolutionary Computation, Anchorage, Alaska (1998), 330-335."
r26  "Sun, M, Aronson, J E, McKeown, P G, and Drinka, D, A tabu search heuristic procedure for the fixed charge transportation problem. European Journal of Operational Research 106 (1998), 441-456."
r27  "MIPLIB 3.0 Library, online at http://www.caam.rice.edu/~bixby/miplib/miplib.html."
r28  "NETLIB Infeasible LP Library, online at http://www.netlib.org/lp/infeas."
r29  "Miscellaneous LP Models, Hungarian Academy of Sciences OR Lab: online at ftp.sztaki.hu/oplab."
r30  "Mittelmann H. - LP Models, Miscellaneous LP models collected by Hans D. Mittelmann: online at ftp://plato.la.asu.edu/pub/lptestset/."
r31  "Mittelmann H. - MIP Models, Miscellaneous MIP models collected by Hans D. Mittelmann: online at ftp://plato.la.asu.edu/pub/milp/."
r32  "Problematic LP Models, Hungarian Academy of Sciences OR Lab: online at ftp.sztaki.hu/oplab."
r33  "Stochastic LP Models, Hungarian Academy of Sciences OR Lab: online at ftp.sztaki.hu/oplab."
r34  "MOSEK ApS, MOSEK Consulting Client Models."
r35  "Mittelmann, H, Miscellaneous MIQCP models by Hans D. Mittelmann: online at ftp://plato.la.asu.edu/pub/miqp/."
r36  "Binous, H, Chemical Engineering Application Models. (Contributed models)"
r37  "Edgar, T F, Himmelblau, D M, and Lasdon, L S, Optimization of Chemical Processes. McGraw Hill, Boston, 2001."
r38  "GAMS Development, GAMS Development Client Models."
/
$onempty
set cr(r,r) cross references /
r11.(r12)
/
set ca(a) credit authors /
"GAMS Dev. Client Models"
/
$offempty
set af(a,r) first author     /
"Andrew Boyd, E".(r18,r19,r20)
"Barutt, J".(r4)
"Bienstock, D".(r7)
"Binous, H".(r36)
"Bixby, R".(r1)
"Bouvier, B".(r9)
"Carolan, W J".(r2)
"Cook, W".(r5,r8)
"Crowder, H".(r17)
"Eckstein, J".(r12,r13,r21)
"Edgar, T F".(r37)
"Gailly, B".(r6)
"GAMS Development".(r38)
"Gottlieb, J".(r25)
"Hoffman, K L".(r16)
"Johnson, E L".(r10)
"Lemke, C".(r15)
"MIPLIB 3.0 Library".(r27)
"Miscellaneous LP Models".(r29)
"Mittelmann H. - LP Models".(r30)
"Mittelmann H. - MIP Models".(r31)
"Mittelmann, H".(r35)
"MOSEK ApS".(r34)
"Nemhauser, G L".(r3)
"NEOS MIP Benchmark".(r24)
"NETLIB Infeasible LP Library".(r28)
"NETLIB LP Repository".(r23)
"Problematic LP Models".(r32)
"Senju, S".(r22)
"Stochastic LP Models".(r33)
"Sun, M".(r26)
"Van Roy, T J".(r14)
/
set ar(a,r) author reference mapping /
"Andrew Boyd, E".(r18,r19,r20)
"Aronson, J E".(r26)
"Barutt, J".(r4)
"Bienstock, D".(r7)
"Binous, H".(r36)
"Bixby, R".(r1)
"Bouvier, B".(r9)
"Carolan, W J".(r2)
"Ceria, S".(r1)
"Cook, W".(r5,r8)
"Crowder, H".(r17)
"Drinka, D".(r26)
"Eckstein, J".(r12,r13,r21)
"Edgar, T F".(r37)
"Gailly, B".(r6)
"GAMS Dev. Client Models".(r38)
"GAMS Development".(r38)
"Gottlieb, J".(r25)
"Hill, J E".(r2)
"Himmelblau, D M".(r37)
"Hoffman, K L".(r16)
"Hull, T".(r4)
"Johnson, E L".(r10,r17)
"Kennington J L".(r2)
"Lasdon, L S".(r37)
"Lemke, C".(r15)
"McKeown, P G".(r26)
"McZeal C M".(r1)
"Messoumian, G".(r9)
"MIPLIB 3.0 Library".(r27)
"Miscellaneous LP Models".(r29)
"Mittelmann H. - LP Models".(r30)
"Mittelmann H. - MIP Models".(r31)
"Mittelmann, H".(r35)
"MOSEK ApS".(r34)
"Nemhauser, G L".(r3)
"NEOS MIP Benchmark".(r24)
"NETLIB Infeasible LP Library".(r28)
"NETLIB LP Repository".(r23)
"Niemi, S".(r2)
"Padberg, M".(r16,r17)
"Paulmann, L".(r25)
"Problematic LP Models".(r32)
"Rutherford, T".(r5)
"Sallcoss, D".(r5)
"Savelsbergh, M W P".(r1)
"Scarf, H E".(r5)
"Senju, S".(r22)
"Spielberg, K".(r15)
"Stochastic LP Models".(r33)
"Suhl, U H".(r10)
"Sun, M".(r26)
"Toyoda, Y".(r22)
"Trick, M A".(r3)
"Van Roy, T J".(r14)
"Wichmann, S J".(r2)
"Wolsey, L A".(r6,r14)
/
