$onEmpty
 x1.L  = 3.4329 ;
 x2.L  = 0.1627 ;
 x3.L  = 0.1139 ;
 x4.L  = 0.2539 ;
 x5.L  = 0.0208 ;
 x6.L  = 2.0247 ;
$offListing
 x7.L  = 1 ;
 x8.L  = 0.0696672 ;
 x9.M  = 1 ;
 x10.L  = 1.92046E-6 ;
 x11.L  = 0.000127303 ;
 x12.L  = 0.00276545 ;
 x13.L  = 0.0294962 ;
 x14.L  = 0.180249 ;
 x15.L  = 0.677981 ;
 x16.L  = 1.33637 ;
 x17.L  = 1 ;
 ;
 e1.M  = 1 ;
 e2.M  = Eps ;
 e3.M  = Eps ;
 e4.M  = Eps ;
 e5.M  = Eps ;
 e6.M  = Eps ;
 ;
 e8.M  = Eps ;
 e9.M  = Eps ;
 e10.M  = Eps ;
 e11.M  = Eps ;
 e12.M  = Eps ;
 e13.M  = Eps ;
 e14.M  = Eps ;
 e15.M  = Eps ;
 e16.M  = Eps ;
 e17.M  = Eps ;
 e18.M  = Eps ;

$offEmpty
$onListing
