$onEmpty
 objvar.L  = -1 ;
 x2.L  = 0.5 ;
 x3.L  = 0.5 ;
 x4.L  = 0.5 ;
 x5.L  = 0.5 ;
 x6.M  = Eps ;
$offListing
 x7.M  = Eps ;
 x8.L  = 1 ;
 x9.L  = 1 ;
 x10.M  = Eps ;
 x11.M  = Eps ;
 x12.M  = 0.5 ;
 x13.M  = 0.5 ;
 ;
 ;
 x16.M  = Eps ;
 x17.M  = Eps ;
 e1.M  = -1 ;
 e2.M  = Eps ;
 e3.M  = Eps ;
 e4.M  = Eps ;
 e5.M  = Eps ;
 ;
 ;
 e8.M  = -0.5 ;
 e9.M  = -0.5 ;
 ;
 ;
 e12.M  = 0.5 ;
 e13.M  = 0.5 ;

$offEmpty
$onListing
