set a authors /
"Andersen, E"
"Boyd, S"
"H. D. Mittelmann"
"Kalvelagen, E"
"Lebret, H"
"Lobo, M S"
"Pataki, G"
"R. Vanderbei"
"Schmieta, S"
"Vandenberghe, L"
"Yu-Ju Kuo"
/
set r references /
r1  "Andersen, E, MOSEK Optimization Tools Manual, online at http://www.mosek.com/documentation.html."
r2  "Lobo, M S, Vandenberghe, L, Boyd, S, and Lebret, H, Applications of Second Order Cone Programming. Linear Algebra and its Applications, Special Issue on Linear Algebra in Control, Signals and Image Processing. 284 (November, 1998)."
r3  "Pataki, G, and Schmieta, S, The DIMACS library of semidefinite-quadratic-linear programs. Tech. rep., Computational Optimization Research Center, Columbia University, 2002."
r4  "Pataki, G, and Schmieta, S, The DIMACS library of semidefinite-quadratic-linear programs, online at http://dimacs.rutgers.edu/Challenges/Seventh/Instances/."
r5  "Kalvelagen, E, Model Building with GAMS. forthcoming"
r6  "R. Vanderbei, Nonlinear Optimization Models (AMPL), See http://www.princeton.edu/~rvdb/ampl/nlmodels/."
r7  "Yu-Ju Kuo, and H. D. Mittelmann, Interior Point Methods for Second Order Cone Programming and OR Applications. Computational Optimization and Applications  (to appear)."
/
$onempty
set cr(r,r) cross references /
/
set ca(a) credit authors /
/
set af(a,r) first author     /
"Andersen, E".(r1)
"Kalvelagen, E".(r5)
"Lobo, M S".(r2)
"Pataki, G".(r3,r4)
"R. Vanderbei".(r6)
"Yu-Ju Kuo".(r7)
/
set ar(a,r) author reference mapping /
"Andersen, E".(r1)
"Boyd, S".(r2)
"H. D. Mittelmann".(r7)
"Kalvelagen, E".(r5)
"Lebret, H".(r2)
"Lobo, M S".(r2)
"Pataki, G".(r3,r4)
"R. Vanderbei".(r6)
"Schmieta, S".(r3,r4)
"Vandenberghe, L".(r2)
"Yu-Ju Kuo".(r7)
/
$offempty
