$onEmpty
 x1.L  = 1 ;
 x1.M  = -3 ;
 x2.L  = 1 ;
 x2.M  = -3 ;
 x3.L  = 1 ;
 x3.M  = -3 ;
$offListing
 x4.L  = 1 ;
 x4.M  = -5 ;
 x5.L  = 1 ;
 x5.M  = -1 ;
 x6.L  = 1 ;
 x6.M  = -1 ;
 x7.L  = 1 ;
 x7.M  = -1 ;
 x8.L  = 1 ;
 x8.M  = -1 ;
 x9.L  = 1 ;
 x9.M  = -1 ;
 x10.L  = 3 ;
 x11.L  = 3 ;
 x12.L  = 3 ;
 x13.L  = 1 ;
 x13.M  = -1 ;
 objvar.L  = -15 ;
 e1.M  = 1 ;
 e2.M  = -0.5 ;
 e3.M  = -0.5 ;
 e4.M  = -0.5 ;
 ;
 ;
 ;
 ;
 ;
 ;

$offEmpty
$onListing
