$onEmpty
 x1.L  = -10 ;
 x2.L  = -10 ;
 ;
 x4.L  = 1 ;
 x4.M  = 2 ;
 x5.M  = 2 ;
 x6.L  = 10 ;
$offListing
 x7.L  = 10 ;
 ;
 x9.L  = 30 ;
 ;
 x11.L  = 30 ;
 ;
 ;
 x14.L  = 20 ;
 ;
 x16.L  = 20 ;
 ;
 e1.M  = -1 ;
 ;
 e3.M  = Eps ;
 e4.M  = Eps ;
 e5.M  = 3 ;
 e6.M  = Eps ;
 e7.M  = 3 ;
 e8.M  = Eps ;
 e9.M  = Eps ;
 e10.M  = Eps ;
 e11.M  = -0.15 ;
 e12.M  = Eps ;
 e13.M  = -0.15 ;
 e14.M  = Eps ;
 e15.M  = Eps ;
 e16.M  = Eps ;

$offEmpty
$onListing
