$onEmpty
 x1.L  = 4800 ;
 x2.L  = 3900 ;
 x3.M  = 10 ;
 x4.L  = 300 ;
 ;
 x6.L  = 100 ;
 x6.M  = -7 ;
$offListing
 x7.L  = 200 ;
 x7.M  = -1 ;
 x8.L  = 1 ;
 x8.M  = 6 ;
 x9.L  = 1 ;
 x9.M  = 6 ;
 x10.L  = 100 ;
 x11.L  = 200 ;
 x12.L  = 1 ;
 objvar.L  = 900 ;
 e1.M  = -1 ;
 e2.M  = 1 ;
 e3.M  = 16 ;
 e4.M  = 16 ;
 e5.M  = -16 ;
 e6.M  = -10 ;
 e7.M  = Eps ;
 ;
 ;
 e10.M  = 1 ;

$offEmpty
$onListing
