* File for PrincetonLib groups and description. Format must
* remain as is (with the column entries remaining at these locations)
* Group                 Description
*
antenna                 Antenna Array Synthesis
"jeffc/antenna"         Antenna Array Synthesis (Coleman)
brachistochrone         Brachistochrone Problem
catenary                Catenary Problem
cute                    Cute Set
dea                     Data Envelopment Analysis
fekete                  Electrons on a Sphere
facloc                  Facility Location Points
firfilter               FIR filter Design
jeffc                   FIR Filter Design (Coleman)
wbv                     "FIR Filter Design (Wu, Boyd, Vandenberghe)"
grasp                   Grasping Force Optimization
springs                 Hanging Chain of Springs
hang                    Hang Glider: Range Maximization
hs                      Hock and Schittkowski Suite
hydrothermal            Hydrothermal Power Coordination
polygon                 Largest Small Polygon
markowitz               Markowitz Models for Portfolio Optimization
median                  Median
minsurf                 Minimal Surfaces
"elena/nlmodels"        Models from Elena Bobrovnikova
nnls                    Nonnegative Least Squares
power                   Power Flow Optimization
puttputt                Putting Trajectories
pca                     Principle Component Analysis
rocket                  Rocket Fastest Trip
sawpath                 Saw Path Tracking
s                       Schittkowski Suite
sdp                     Semidefinite Programming
steiner                 Steiner Problems
stengel                 Stengel Problems
structure               Structural Optimization
braess                  Traffic Equilibrium
robotarm                Trajectory Optimization