set a authors /
"Abate, M"
"ACC"
"Ackermann, J"
"Adhya, N"
"Adjiman, C S"
"Aggarwal, A"
"Ahmed, S"
"Aiyoshi, E"
"Al-Khayyal, F A"
"Anandalingam, G"
"Anitescu, M"
"ARKI Consulting"
"Arnold, K J"
"Ascher, U M"
"Ashrafi, N"
"Averick, B M"
"Avriel, M"
"Bard, J F"
"Barmish, B R"
"Beck, J V"
"Beltramo, M A"
"Ben-Sadd, S"
"Ben-Tal, A"
"Berman, O"
"Berna, T"
"Betts, J"
"Biegler, L T"
"Binous, H"
"Blitzer, C"
"Bondarenko, A S"
"Borland"
"Box, G E P"
"Bracken, J"
"Brennecke, J"
"Brooke, A"
"Bryson, A E"
"Bulirsch, R"
"Bullard, L G"
"Candler, W"
"Capriz, G"
"Carlson, R C"
"Carter, R G"
"Castillo, J"
"Cesari, L"
"Chenery, H B"
"Chou, C"
"Cimatti, G"
"Ciric, A R"
"Clark, P A"
"Coello Coello, C A"
"Colville, A R"
"Condon, T"
"Csendes, T"
"Dahl, H"
"Dallwig, S"
"de Gaston, R"
"Deaven, D M"
"Deb, K"
"Dembo, R S"
"den Hertog, D"
"Devarajan, S"
"Dixon, L"
"Dolan, E D"
"Domenech, S"
"Drud, A"
"Drud, A S"
"Edgar, T F"
"Eiger, G"
"Eldersveld, S"
"Erjavec, J"
"Esposito, W R"
"Fair, R C"
"Falk, J E"
"Fasano, A"
"Ferraris, G B"
"Floudas, C A"
"Fredenslund, A"
"Friedman, A"
"GAMS Development"
"GAMS Software GmbH"
"Gay, D M"
"Gershovitz, V"
"Gill, P E"
"Glowinski, R"
"Goldstein, A"
"Goyal, M"
"Graham, R L"
"Green, K"
"Greenberg, B"
"Greening, D"
"Griffin, O H"
"Grossmann, I E"
"Gumus, Z H"
"Gurdal, Z"
"Hancil, V"
"Handbook of Test Problems"
"Hansen, E"
"Harding, S T"
"Harker, P T"
"Hart, S M"
"Haverly, C A"
"Heidemann, R"
"Hesse, R"
"Himmelblau, D M"
"Hlavacek, V"
"Ho, K M"
"Ho, Y"
"Hock, W"
"Hofmann, H"
"Hua, J"
"Huffman, W"
"Hunter, W G"
"Ishizuka, Y"
"Kaesbauer, D"
"Kalantari, B"
"Kasnagoklu, H"
"Kearfott, R"
"Kendrick, D"
"Kim, I"
"Kim, Y S"
"Klepeis, J L"
"Kocis, G R"
"Konno, H"
"Kubicek, M"
"Kuhn, H W"
"Kuijlaars, A"
"Kuno, T"
"Kutcher, G P"
"Lasdon, L S"
"Le-Si, V"
"Leclerc, A"
"Lewis, J"
"Li, H"
"Liebman, J"
"Liebman, M J"
"Liu, J"
"Liu, Y H"
"Locke, M"
"Luks, K"
"Lundqvist K."
"MacGregor, J F"
"Magnussen, T"
"Mandhane, J"
"Mangasarian, O L"
"Manne, A S"
"Manousiouthakis, V"
"Maranas, C D"
"Maria, G"
"Marin, R"
"Mathematica"
"Mattheij, R M M"
"McCormick, G P"
"McDonald, C M"
"Meeraus, A"
"Meintjes, K"
"Meyer, C A"
"Michelsen, M L"
"Migdalas, A"
"Mitra, P"
"Moore, R E"
"Morari, M"
"More, J J"
"Morgan, A P"
"Morris, J R"
"Muench, R"
"Mulvey, J"
"Murillo-Sanchez, C"
"Murray, W"
"Murtagh, B A"
"Nelson, C R"
"Nemhauser, G L"
"Nerz, E"
"Neumaier, A"
"Norton, R D"
"Novoa, M"
"O'Mara, G T"
"Pardalos P M"
"Pardalos, P M"
"Paules IV, G E"
"Pesch, H J"
"Pibouleau, L"
"Pindyck, R S"
"Pinter, J D"
"Plummer, J"
"Polocsay, S W"
"Price, J"
"Primicerio, M"
"Raduchel, W J"
"Ragsdell, K"
"Ramsey, F P"
"Rasmussen, P"
"Ratschek, H"
"Ratz, D"
"Reklaitis, G"
"Robinson, S"
"Rod, V"
"Rokne, J"
"Rosen, J B"
"Rosenborg, A"
"Rosenbrock, H H"
"Rothschild, B J"
"Russell, R D"
"Ryoo, H S"
"Saff, E B"
"Safonov, M"
"Sahinidis, N"
"Sanchez"
"Sandgren, E"
"Sargent, R"
"Saunders, M A"
"Scandizzo, P L"
"Schaible, S"
"Schittkowski, K"
"Schrage, L"
"Schweiger, C A"
"Serban, R"
"Shah, J V"
"Sharov, A F"
"Shectman, J P"
"Shimizu, K"
"Shin, D K"
"SIAM"
"Siddall, J N"
"Sideris, A"
"Sinkule, J"
"Smith, J"
"So, K C"
"Sodini, C"
"Soland, R M"
"Sourlas, D"
"Stadtherr, M"
"Stehouwer, H P"
"Stephanopoulos, G"
"Stinstra, E"
"Stoecker, W F"
"Stoutjesdijk, A J"
"Swaney, R E"
"Szegoe, G P"
"Tawarmalani, M"
"Taylor, L"
"Tempo, R"
"Tendulkar, S"
"Tesi, A"
"Thai, N Q"
"Thakur, L S"
"Thieu, T V"
"Thoai, N V"
"Tjoa, I B"
"Townsley, R"
"Tronconi, E"
"Tsai, L -"
"Tuy, H"
"University of Cagliari"
"Vanderbei, R"
"Varbrand, P"
"Vestjens, A"
"Vicino, A"
"Visweswaran, V"
"von Stryk, O"
"Wall, T W"
"Waren, A D"
"Westerberg, A W"
"Westerlund, T"
"Weyant, J P"
"White, D J"
"Wilkinson, J H"
"Williams, A C"
"Wingo, D"
"Wollenberg, B F"
"Wood, A J"
"Woolsey, R E D"
"Wright, M H"
"Xia, Q"
"Xue, G L"
"Yajima, Y"
"Yezza, A"
"Yu, M"
"Yuan, X"
"Zenios, S A"
"Zhang, S"
"Zhou, S"
/
set r references /
r1  "Floudas, C A, Pardalos, P M, Adjiman, C S, Esposito, W R, Gumus, Z H, Harding, S T, Klepeis, J L, Meyer, C A, and Schweiger, C A, Handbook of Test Problems in Local and Global Optimization. Kluwer Academic Publishers, 1999."
r2  "Wingo, D, Globally Minimizing Polynomials Without Evaluating Derivatives. Intl. J. Comput. Math 17, 287 (1985)."
r3  "Moore, R E, Methods and Applications of Interval Analysis. Prentice Hall, Englewood Cliffs, NJ, 1979."
r4  "Wilkinson, J H, Rounding Errors in Algebraic Processes. Prentice Hall, Englewood Cliffs, NJ, 1963."
r5  "University of Cagliari, Ed, Proceedings of a Workshop at the University of Cagliari, Italy, 1975."
r6  "Dixon, L, and Szegoe, G P, Towards Global Optimization. In University of Cagliari, Ed, Proceedings of a Workshop at the University of Cagliari, Italy. North Holland, 1975."
r7  "Goldstein, A, and Price, J, On Descent From Local Minima. Mathematics of Computation 25 (1971), 569-574."
r8  "SIAM, Ed, SIAM National Meeting, 1990."
r9  "Dixon, L, On Finding the Global Minimum of a Function of One Variable. In SIAM, Ed, SIAM National Meeting. Chicago, 1990."
r10  "Maranas, C D, and Floudas, C A, Global Minimum Potential Energy Conformations of Small Molecules. Journal of Global Optimization 4 (1994), 135-170."
r11  "Soland, R M, An Algorithm for Separable Nonconvex Programming Problems ii : Nonconvex Constraints. Mgnt. Sci. 17 (1971), 759."
r12  "Adjiman, C S, Dallwig, S, Floudas, C A, and Neumaier, A, A Global Optimization Method, aBB, For General Twice-Differentiable NLPs - I. Theoretical Advances. Comput. Chem. Eng. 22 (1998), 1137-1158."
r13  "Bullard, L G, and Biegler, L T, Iterative Linear-Programming Strategies for Constrained Simulation. Comput. Chem. Eng. 15 (1991), 239-254."
r14  "Ferraris, G B, and Tronconi, E, BUNLSI - a FORTRAN Program for Solution of Systems of Nonlinear Algebraic Equations. Comput. Chem. Eng. 10 (1986), 129-141."
r15  "Ben-Sadd, S, An Algorithm for a Class of Nonlinear Nonconvex Optimization Problems. PhD thesis, University of California, Los Angeles, 1989."
r16  "ACC, Ed, Proc. ACC, Atlanta, GA, 1988."
r17  "Sideris, A, and Sanchez, Fast Computation of the Multivariable Stability Margin for Real Interrelated Uncertain Parameters. In ACC, Ed, Proc. ACC, Atlanta, GA. 1988."
r18  "Yezza, A, First-Order Necessary Optimality Conditions for General Bilevel Programming Problems. Journal of Optimization Theory and Applications 89 (1996), 189-219."
r19  "Kuhn, H W, Ed, Princeton Symposium on Mathematical Programming. Princeton Univ. Press, 1970."
r20  "Colville, A R, A Comparative Study of Nonlinear Programming Codes. In Kuhn, H W, Ed, Princeton Symposium on Mathematical Programming. Princeton Univ. Press, 1970."
r21  "Ackermann, J, Kaesbauer, D, and Muench, R, Robust Gamma-Stability Analysis in a Plant Parameter Space. Automatica 27 (1991), 75."
r22  "Murtagh, B A, and Saunders, M A, MINOS 5.4 User's Guide. Tech. rep., Systems Optimization Laboratory, Department of Operations Research, 1993."
r23  "Hesse, R, A Heuristic Search Procedure for Estimating a Global Solution of Nonconvex Programming Problems. Op. Res. 21 (1973), 1267."
r24  "Ryoo, H S, and Sahinidis, N, Global Optimization of Nonconvex NLPs and MINLPs with Applications in Process Design. Comput. Chem. Eng 19 (1995), 551-566."
r25  "Ben-Tal, A, Eiger, G, and Gershovitz, V, Global Minimization by Reducing the Duality Gap. Mathematical Programming 63 (1994), 193-212."
r26  "Hock, W, and Schittkowski, K, Test Examples for Nonlinear Programming Codes, Lecture Notes in Economics and Mathematical Systems. Springer Verlag, 1981."
r27  "Hock, W, and Schittkowski, K, Text Examples for Nonlinear Programming Codes. In Test Examples for Nonlinear Programming Codes, Lecture Notes in Economics and Mathematical Systems. Springer Verlag, 1981."
r28  "Avriel, M, and Williams, A C, An Extension of Geometric Programming with Applications in Engineering Optimization. Journal of Engineering Mathematics 5 (1971), 187-194."
r29  "Clark, P A, and Westerberg, A W, Bilevel Programming for Steady-State Chemical Process Design-i. Fundamentals and Algorithms. Comput. Chem. Eng. 14 (1990), 87."
r30  "Green, K, Zhou, S, and Luks, K, The Fractal Response of Robust Solution Techniques to the Stationary Point Problem. Fluid Phase Equilibria 84 (1993), 49-78."
r31  "Liu, Y H, and Hart, S M, Characterizing an Optimal Solution to the Linear Bilevel Programming Problem. European Journal of Operational Research 79 (1994), 164-166."
r32  "Clark, P A, and Westerberg, A W, A Note on the Optimality Conditions for the Bilevel Programming Problem. Naval Research Logistics 35 (1988), 413-418."
r33  "Shimizu, K, and Aiyoshi, E, A New Computational Method for Stackelberg and Mim-Max Problems by Use of a Penalty Method. IEEE Trans. on Aut. Control 26 (1981)."
r34  "Floudas, C A, and Pardalos, P M, Eds, State of the Art in Global Optimization. Kluwer Academic Publishers, 1996."
r35  "Visweswaran, V, A Decomposition-Based Global Optimization Approach for Solving Bilevel Linear and Quadratic Programs. In Floudas, C A, and Pardalos, P M, Eds, State of the Art in Global Optimization. Kluwer Academic Publishers, 1996, p. 139."
r36  "Vicino, A, and Tesi, A, Computation of Nonconservative Stability Perturbation Bounds for Systems with Nonlinearly Correlated Uncertainties. IEEE Trans. Autom. Contr 35 (1990), 835."
r37  "Bard, J F, Some Properties of the Bilevel Programming Problem. Journal of Optimization Theory and Applications 68 (1991), 371-378."
r38  "Tuy, H, Migdalas, A, and Varbrand, P, A Global Optimization Approach for the Linear Two-Level Program. Journal of Global Optimization 3 (1993), 1."
r39  "Bard, J F, and Falk, J E, An Explicit Solution to the Multi-Level Programming Problem. Comp. Op. Res. 9 (1982), 77-100."
r40  "Grossmann, I E, Ed, Global Optimization in Engineering Design. Kluwer Books, 1996."
r41  "Visweswaran, V, and Floudas, C A, Computational Results for an Efficient Implementation of the GOP Algorithm and its Variants. In Grossmann, I E, Ed, Global Optimization in Engineering Design. Kluwer Books, 1996."
r42  "Floudas, C A, and Ciric, A R, Eds, Proceedings of the Third International Symposium on Process Systems Engineering, 1988."
r43  "Floudas, C A, and Ciric, A R, Global Optimum Issues on Heat Exchanger Networks Synthesis. In Floudas, C A, and Ciric, A R, Eds, Proceedings of the Third International Symposium on Process Systems Engineering. Sydney, Australia, 1988."
r44  "Floudas, C A, Nonlinear and Mixed Integer Optimization: Fundamentals and Applications. Oxford University Press, 1995."
r45  "Kocis, G R, and Grossmann, I E, Global Optimization of Nonconvex MINLP Problems in Process Synthesis. Industrial and Engineering Chemical Research 27 (1988), 1407-1421."
r46  "Yuan, X, Zhang, S, and Pibouleau, L, A Mixed-Integer Nonlinear-Programming Method for Process Design. RAIRO - Recherche Operationnelle-Operations Research 22 (1988), 331-346."
r47  "Anandalingam, G, and White, D J, A Solution Method for the Linear Static Stackelberg Problem Using Penalty Functions. IEEE Trans. Auto. Contr. 35 (1990), 1170-1173."
r48  "Candler, W, and Townsley, R, A Linear Two-Level Programming Problem. Comp. Op. Res. 9 (1982), 59-76."
r49  "Berman, O, and Ashrafi, N, Optimization Models for Reliability of Modular Software Systems. IEEE Transactions on Software Engineering 19, 11 (1993), 1119-1123."
r50  "Smith, J, Chemical Engineering Kinetics. Butterworth, Stoneham, MA, 1985."
r51  "Reklaitis, G, and Ragsdell, K, Engineering Optimization. John Wiley and Sons, New York, NY, 1983."
r52  "McDonald, C M, Global Optimization for the Phase and Chemical Equilibrium Problem. PhD thesis, Princeton University, 1995."
r53  "McDonald, C M, and Floudas, C A, Global Optimization for the Phase Stability Problem. AIChE J. 41 (1995), 1798."
r54  "Kubicek, M, Hofmann, H, Hlavacek, V, and Sinkule, J, Multiplicity and Stability in a Sequence of Two Nonadiabatic Nonisothermal CSTRS. Chem. Engng. Sci. 35 (1980), 987."
r55  "McDonald, C M, and Floudas, C A, GLOPEQ: A New Computational Tool for the Phase and Chemical Equilibrium Problem. Comput. Chem. Eng. 21 (1997), 1-23."
r56  "McDonald, C M, and Floudas, C A, Global Optimization and Analysis for the Gibbs Free Energy Function Using the UNIFAC, Wilson and ASOG Equations. I and EC Res. 34 (1995), 1674."
r57  "Heidemann, R, and Mandhane, J, Some Properties of the NRTL Equation in Correcting Liquid-Liquid Equilibrium Data. Chem. Eng. Sci. 28 (1973), 1213."
r58  "de Gaston, R, and Safonov, M, Exact Calculation of the Multi-Loop Stability Margin. IEEE Trans. Automat. Contr. 33 (1988), 68."
r59  "Meintjes, K, and Morgan, A P, Chemical-Equilibrium Systems as Numerical Test Problems. ACM Trans. Math. Soft. 16 (1990), 143-151."
r60  "Kearfott, R, and Novoa, M, INTBIS, A Portable Interval Newton Bisection Package. ACM Trans. Math. Soft. 16 (1990), 152-157."
r61  "McDonald, C M, and Floudas, C A, Global Optimization for the Phase and Chemical Equilibrium Problem: Application to the NRTL Equation. Comput. Chem. Eng. 19 (1995), 1."
r62  "Magnussen, T, Rasmussen, P, and Fredenslund, A, UNIFAC Parameter Table for Prediction of Liquid-Liquid Equilibria. I and EC Proc. Des. Dev. 26 (1981), 159."
r63  "Manousiouthakis, V, and Sourlas, D, A Global Optimization Approach to Rationally Constrained Rational Programming. Chem. Eng. Comm. 115 (1992), 127."
r64  "Maranas, C D, and Floudas, C A, Global Optimization in Generalized Geometric Programming. Comput. Chem. Eng. 21 (1997), 351-370."
r65  "Dembo, R S, A Set of Geometric Programming Test Problems and Their Solutions. Math. Prog. 10 (1976), 192-213."
r66  "Falk, J E, and Liu, J, On Bilevel Programming, Part i: General Nonlinear Cases. Mathematical Programming 70 (1995), 47."
r67  "Hua, J, Brennecke, J, and Stadtherr, M, Enhanced Interval Analysis for Phase Stability: Cubic Equation of State Models. I and EC res. 37 (1998), 1519-1527."
r68  "Shimizu, K, Ishizuka, Y, and Bard, J F, Nondifferentiable and Two-Level Mathematical Programming. Kluwer Academic Publishers, 1997."
r69  "Ratschek, H, and Rokne, J, A Circuit Design Problem. J. Global Opt. 3 (1993), 501."
r70  "Castillo, J, and Grossmann, I E, Computation of Phase and Chemical Equilibria. Comput. Chem. Eng. 5 (1981), 99."
r71  "Michelsen, M L, The Isothermal Flash Problem - Part i. Stability. Fluid Phase Equilibria 9 (1982), 1."
r72  "Floudas, C A, and Pardalos P M, Eds, Recent Advances in Global Optimization. Princeton University Press, 1992."
r73  "Moore, R E, Hansen, E, and Leclerc, A, Rigorous Methods for Global Optimization. In Floudas, C A, and Pardalos P M, Eds, Recent Advances in Global Optimization. Princeton University Press, 1992."
r74  "Esposito, W R, and Floudas, C A, Global Optimization in Parameter Estimation of Nonlinear Algebraic Models via the Error-in-Variables Approach. Ind. Eng. Chem. Res. 35 (1998), 1841-1858."
r75  "Barmish, B R, New Tools for Robustness of Linear Systems. MacMillan Publishing Company, New York, NY, 1994."
r76  "Abate, M, Barmish, B R, Murillo-Sanchez, C, and Tempo, R, Application of Some New Tools to Robust Stability Analysis of Spark Ignition Engines : A Case Study. IEEE Trans. Contr. Syst. Tech. 2 (1994), 22."
r77  "Csendes, T, and Ratz, D, Subdivision Direction Selection in Interval Methods for Global Optimization. Journal of Global Optimization 7 (1995), 183."
r78  "Tjoa, I B, and Biegler, L T, Reduced Successive Quadratic Programming Strategy for Errors-in-Variables Estimation. Comp. Chem. Engng 16 (1992), 523."
r79  "Rod, V, and Hancil, V, Iterative Estimation of Model Parameters When Measurements of All Variables are Subject to Error. Comp. Chem. Engng 4 (1980), 33."
r80  "Grossmann, I E, and Sargent, R, Optimal Design of Multipurpose Chemical Plants. Ind. Eng. Chem. Proc. Des. Dev. 18 (1979), 343."
r81  "Harding, S T, and Floudas, C A, Global Optimization in Multiproduct and Multipurpose Batch Design Under Uncertainty. I and EC Res. 36 (1997), 1644-1664."
r82  "Kim, I, Liebman, M J, and Edgar, T F, Robust Error-in-Variables Estimation Using Nonlinear Programming Techniques. AIChE 36 (1990), 985."
r83  "Haverly, C A, Studies of the Behavior of Recursion for the Pooling Problem. ACM SIGMAP Bull 25 (1978), 19-28."
r84  "Aggarwal, A, and Floudas, C A, Synthesis of General Distillation Sequences: Nonsharp Separation. Computers and Chemical Engineering 14, 6 (1990), 631-653."
r85  "Schweiger, C A, and Floudas, C A, Optimization Framework for the Synthesis of Chemical Reactor Networks. Ind. Eng. Chem. Res. (1998)."
r86  "Esposito, W R, and Floudas, C A, Parameter Estimation of Nonlinear Algebraic Models via Global Optimization. Comput. Chem. Eng. 22 (1998), S213-S220."
r87  "Tjoa, I B, and Biegler, L T, Simultaneous Solution and Optimization Strategies for Parameter Estimation of Differential-Algebraic Equations Systems. Ind. Eng. Chem. Res. 30 (1991), 376-385."
r88  "Averick, B M, Carter, R G, More, J J, and Xue, G L, The MINPACK-2 Test Problem Collection. Tech. rep., Mathematics and Computer Science Division, Argonne National Laboratory, 1992."
r89  "Maria, G, An Adaptive Strategy for Solving Kinetic Model Concomitant Estimation - Reduction Problems. Can. J. Chem. Eng. 67 (1989), 825."
r90  "Glowinski, R, Numerical Methods for Nonlinear Variational Problems. Springer Verlag, 1984."
r91  "Friedman, A, Free Boundary Problems in Science and Technology. Notices Amer. Math. Soc. 47 (2000), 854-861."
r92  "Morris, J R, Deaven, D M, and Ho, K M, Genetic Algorithm Energy Minimization for Point Charges on a Sphere. Phys. Rev. B. 53 (1996), R1740-R1743."
r93  "Saff, E B, and Kuijlaars, A, Distributing Many Points on the Sphere. Math. Intelligencer 19 (1997), 5-11."
r94  "Ascher, U M, Mattheij, R M M, and Russell, R D, Numerical Solution of Boundary Value Problems for Ordinary Differential Equations. SIAM, 1995."
r95  "Bryson, A E, Dynamic Optimization. Addison Wesley, 1999."
r96  "Bulirsch, R, Ed, Optimal Control. Birkhauser Verlag, 1993."
r97  "Bulirsch, R, Nerz, E, Pesch, H J, and von Stryk, O, Combining Direct and Indirect Methods in Nonlinear Optimal Control: Range Maximization of a Hang Glider. In Bulirsch, R, Ed, Optimal Control. Birkhauser Verlag, 1993, pp. 273-288."
r98  "Cesari, L, Optimization - Theory and Applications. Springer Verlag, 1983."
r99  "Box, G E P, Hunter, W G, MacGregor, J F, and Erjavec, J, Some Problems Associated with the Analysis of Multiresponse Data. Technometrics 15 (1973), 33-51."
r100  "Graham, R L, The Largest Small Hexagon. J. Combin. Th. 18 (1975), 165-170."
r101  "Betts, J, Eldersveld, S, and Huffman, W, Sparse Nonlinear Programming Test Problems. Tech. rep., Boeing Computer Services, 1993."
r102  "Rothschild, B J, Sharov, A F, and Bondarenko, A S, Estimating Growth and Mortality in Stage-Structured Populations. Journal of Plankton Research 19 (1997), 1913-1928."
r103  "Vanderbei, R, Nonlinear Optimization Models."
r104  "Anitescu, M, and Serban, R, A Sparse Superlinearly Convergent SQP with Applications to Two-Dimensional Shape Optimization. Tech. rep., Argonne National Laboratory, 1998."
r105  "Gay, D M, AMPL Models."
r106  "Fasano, A, and Primicerio, M, Eds, Research Notes in Mathematics. Pitman, 1983."
r107  "Capriz, G, and Cimatti, G, Free Boundary Problems in the Theory of Hydrodynamic Lubrication: A Survey. In Fasano, A, and Primicerio, M, Eds, Research Notes in Mathematics. Pitman, 1983, pp. 613-635."
r108  "von Stryk, O, User's Guide for DIRCOL (Version 2.1): A Direct Collocation Method for the Numerical Solution of Optimal Control Problems. Tech. rep., Technische Universitat Munchen, 1999."
r109  "Bryson, A E, and Ho, Y, Applied Optimal Control: Optimization, Estimation, and Control. John Wiley and Sons, 1975."
r110  "Dolan, E D, and More, J J, Benchmarking Optimization Software with COPS. Tech. rep., Mathematics and Computer Science Division, 2000."
r111  "Adhya, N, Tawarmalani, M, and Sahinidis, N, A Lagrangian Approach to the Pooling Problem. Industrial and Engineering Chemical Research 38 (1999), 1956-1972."
r112  "Morari, M, and Grossmann, I E, Eds, Chemical Engineering Optimization Models with GAMS. Computer Aids for Chemical Engineering Corporation, 1991."
r113  "Lewis, J, and Robinson, S, Chapter 11. In Chenery, H B, Robinson, S, and Syrquin, M, Eds, Industrialization and Growth: A Comparative Study. Oxford University Press, London, 1986."
r114  "Mitra, P, Adjustments in Oil Importing Developing Countries: A Comparative Economic Analysis. Cambridge University Press, New York, NY, 1993."
r115  "Mitra, P, and Tendulkar, S, Coping with Internal and External Exogenous Shocks: India. Tech. rep., The World Bank, 1986."
r116  "Condon, T, Dahl, H, and Devarajan, S, Implementing a Computable General equilibrium Model on GAMS - The Cameroon Model. Tech. rep., The World Bank, 1987."
r117  "Siddall, J N, Optimal Engineering Design: Principles and Applications. Marcel Dekker, New York, 1982."
r118  "Deb, K, and Goyal, M, Optimizing Engineering Designs Using a Combined Genetic Search. In Back, T, Ed, Proceedings of the Seventh International Conference on Genetic Algorithms. 1997, pp. 521-528."
r119  "Coello Coello, C A, Treating Constraints as Objectives for Single-Objective Evolutionary Optimization. Engineering Optimization 32 (2000), 275-308."
r120  "Gill, P E, Murray, W, and Saunders, M A, GAMS/SNOPT: An SQP Algorithm for Large-Scale Constrained Optimization."
r121  "Carlson, R C, and Nemhauser, G L, Scheduling to Minimize Interaction Cost. Operations Research 14 (1966), 52-58."
r122  "Brooke, A, Kendrick, D, and Meeraus, A, GAMS: A User's Guide. The Scientific Press, Redwood City, California, 1988."
r123  "Berna, T, Locke, M, and Westerberg, A W, A New Approach to Optimization of Chemical Processes. American Institute of Chemical Engineers Journal 26, 1 (1980), 37-43."
r124  "Floudas, C A, and Paules IV, G E, A Mixed-Integer Nonlinear Programming Formulation for the Synthesis of Heat Integrated Distillation Sequence. Computers and Chemical Engineering 12, 6 (1988), 531-546."
r125  "Borland, Eureka: The Solver, Borland International, Scotts Valley, California, 1987."
r126  "Mangasarian, O L, Nonlinear Programming. McGraw Hill, New York, 1973."
r127  "Kutcher, G P, Meeraus, A, and O'Mara, G T, Agriculture Sector and Policy Models. The World Bank, 1988."
r128  "Le-Si, V, Scandizzo, P L, and Kasnagoklu, H, Turkey Agricultural Sector Model. Tech. rep., The World Bank, 1982."
r129  "Harker, P T, Alternative Models of Spatial Competition. Operations Research 34, 3 (1986), 410-425."
r130  "Wright, M H, Numerical Methods for Nonlinearly Constraint Optimization. PhD thesis, Stanford University, 1976."
r131  "Rosenbrock, H H, An Automatic Method for finding the Greatest or least value of a function. Computer Journal 3 (1960), 175-184."
r132  "Manne, A S, ETA-MACRO: A Model of Energy-Economy Interactions. In Hitch, C J, Ed, Modeling Energy-Economy Interactions: Five Approaches. Resources for the Future, Washington, DC, 1977."
r133  "Zenios, S A, Drud, A S, and Mulvey, J, Balancing some large Social Accounting Matrices with Nonlinear Programming. Tech. rep., Department of Civil Engineering, Princeton University, 1986."
r134  "Wall, T W, Greening, D, and Woolsey, R E D, Solving Complex Chemical Equilibria Using a Geometric-Programming Based Technique. Operations Research 34, 3 (1987)."
r135  "Fair, R C, Specification, Estimation, and Analysis of Macroeconomic Models. Harvard University Press, Cambridge, Mass, 1984."
r136  "Kendrick, D, Caution and Probing in a Macroeconomic Model. Journal of Economic Dynamics and Control 4, 2 (1982)."
r137  "Ramsey, F P, A Mathematical Theory of Saving. Economics Journal (1928)."
r138  "Murtagh, B A, and Saunders, M A, A Projected Lagrangian Algorithm and its Implementation for Sparse Nonlinear Constraints. Mathematical Programming Study 16 (1982), 84-117."
r139  "Manne, A S, and Beltramo, M A, GTM: An International Gas Trade Model ,International Energy Program Report. Stanford University, 1984."
r140  "Manne, A S, Nelson, C R, So, K C, and Weyant, J P, CPM: A Contingency Planning Model of the International Oil Market, International Energy Program Report. Tech. rep., Stanford University, 1982."
r141  "Blitzer, C, Meeraus, A, and Stoutjesdijk, A J, A Dynamic model of OPEC Trade and Production. Journal of Development Economics, 2 (1975), 318-335."
r142  "Norton, R D, and Scandizzo, P L, Market Equilibrium Computations in Activity Analysis Models. Operations Research 29, 2 (1981)."
r143  "Kendrick, D, and Taylor, L, Numerical methods and Nonlinear Optimizing models for Economic Planning. In Chenery, H B, Ed, Studies of Development Planning. Harvard University Press, 1971."
r144  "Pindyck, R S, Gains to Producers from the Cartelization of Exhaustible Resources. Review of Economics and Statistics 60 (1978), 238-251."
r145  "Wood, A J, and Wollenberg, B F, Example Problem 7b. In Power Generation, Operation and Control. John Wiley and Sons, 1984, p. 202."
r146  "Wood, A J, and Wollenberg, B F, Example Problem 4e. In Power Generation, Operation and Control. John Wiley and Sons, 1984, pp. 85-88."
r147  "Bracken, J, and McCormick, G P, Chapter 7. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 58-82."
r148  "Dahl, H, Meeraus, A, and Zenios, S A, Some Financial Optimization Models: Risk Management. In Zenios, S A, Ed, Financial Optimization. Cambridge University Press, New York, NY, 1993."
r149  "Himmelblau, D M, Problem Number 11. In Applied Nonlinear Programming. Mc Graw Hill, New York, 1972."
r150  "Brooke, A, Drud, A S, and Meeraus, A, Modeling Systems and Nonlinear Programming in a Research Environment. In Ragavan, R, and Rohde, S M, Eds, Computers in Engineering, Vol. III. ACME, 1985."
r151  "Drud, A S, and Rosenborg, A, Dimensioning Water Distribution Networks. Masters thesis, Institute of Mathematical Statistics and Operations Research, Technical University of Denmark, 1973. (in Danish)"
r152  "Himmelblau, D M, Problem Number 16. In Applied Nonlinear Programming. Mc Graw Hill, New York, 1972."
r153  "Chenery, H B, and Raduchel, W J, Substitution and Structural Change. In Chenery, H B, Ed, Structural Change and Development Policy. Oxford University Press, New York and Oxford, 1979."
r154  "Bracken, J, and McCormick, G P, Chapter 10.2. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968."
r155  "Bracken, J, and McCormick, G P, Chapter 9. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 94-100."
r156  "Bracken, J, and McCormick, G P, Chapter 8.5. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 90-92."
r157  "Bracken, J, and McCormick, G P, Chapter 8.4. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 89-90."
r158  "Bracken, J, and McCormick, G P, Chapter 8.2. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 86-88."
r159  "Bracken, J, and McCormick, G P, Chapter 6. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968."
r160  "Bracken, J, and McCormick, G P, Chapter 5. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 48-49."
r161  "Bracken, J, and McCormick, G P, Chapter 4. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968."
r162  "Bracken, J, and McCormick, G P, Chapter 2. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 22-27."
r163  "Bracken, J, and McCormick, G P, Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968."
r164  "Himmelblau, D M, Applied Nonlinear Programming. Mc Graw Hill, New York, 1972."
r165  "Wood, A J, and Wollenberg, B F, Power Generation, Operation and Control. John Wiley and Sons, 1984."
r167  "Tawarmalani, M, and Sahinidis, N, Convexification and Global Optimization in Continuous and Mixed-Integer Nonlinear Programming: Theory, Algorithms, Software, and Applications. Kluwer, 2002."
r168  "Sahinidis, N, and Grossmann, I E, Convergence properties of generalized Benders' decomposition. Computers and Chemical Engineering 15 (1991), 481-491."
r169  "Stoecker, W F, Design of Thermal Systems. McGraw Hill Book Co., New York, 1971."
r170  "Liebman, J, Lasdon, L S, Schrage, L, and Waren, A D, Modeling and Optimization with GINO. The Scientific Press, Palo Alto, CA, 1986."
r171  "Swaney, R E, Global solution of algebraic nonlinear programs, 1990. American Institute of Chemical Engineers, Annual Meeting, Chicago, IL"
r172  "Westerberg, A W, and Shah, J V, Assuring a global optimum by the use of an upper bound on the lower (dual) bound. Computers and Chemical Engineering 2 (1978), 83-92."
r173  "Stephanopoulos, G, and Westerberg, A W, The use of Hestenes' method of multipliers to resolve dual gaps in engineering system optimization. Journal of Optimization Theory and Applications 15 (1975), 285-309."
r174  "Yuan, X, Zhang, S, Pibouleau, L, and Domenech, S, Une methode d'optimisation non lineaire en variables mixtes pour la conception de procedes. Recherche Operataionnelle/Operations Research 22 (1988), 331-346."
r175  "Floudas, C A, and Ciric, A R, Strategies for overcoming uncertainties in heat exchanger network synthesis. Computers and Chemical Engineering 13 (1989), 1133-1152."
r176  "Visweswaran, V, and Floudas, C A, A global optimization algorithm (GOP) for certain classes of nonconvex NLPs---II. Applications of theory and test problems. Computers and Chemical Engineering 14 (1990), 1419-1434."
r177  "Tuy, H, Thieu, T V, and Thai, N Q, A conical algorithm for globally minimizing a concave function over a closed convex set. Mathematics of Operations Research 10 (1985), 498--514."
r178  "Kalantari, B, and Rosen, J B, An algorithm for global minimization of linearly constrained convex quadratic functions. Mathematics of Operations Research 12 (1987), 544--561."
r179  "Al-Khayyal, F A, and Falk, J E, Jointly constrained biconvex programming. Mathematics of Operations Research 8 (1983), 273-286."
r180  "Konno, H, and Kuno, T, Linear multiplicative programming. Mathematical Programming 56 (1992), 51-64."
r181  "Thoai, N V, A global optimization approach for solving convex multiplicative programming problems. Journal of Global Optimization 1 (1991), 341-357."
r182  "Falk, J E, and Soland, R M, An algorithm for separable nonconvex programming problems. Management Science 15 (1969), 550-569."
r183  "Sahinidis, N, Tawarmalani, M, and Yu, M, Design of alternative refrigerants via global optimization, 2002. (in preparation)"
r184  "Li, H, and Chou, C, A global approach for nonlinear mixed discrete programming in design optimization. Engineering Optimization 22 (1994), 109-122."
r185  "Shin, D K, Gurdal, Z, and Griffin, O H, A penalty approach for nonlinear optimization with discrete design variables. Engineering Optimization 16 (1990), 29--42."
r186  "Kim, Y S, Problems in reliability, 1998. Personal Communication"
r187  "Thakur, L S, Domain contraction in nonlinear programming: Minimizing a quadratic concave function over a polyhedron. Mathematics of Operations Research 16 (1990), 390-407."
r188  "Ashrafi, N, and Berman, O, Optimization models for selection of programs, considering cost and reliability. IEEE Trans. Reliab.  41 (1992), 281-287."
r189  "Marin, R, Points of location on a fixture, 1998. Personal Communication"
r190  "Xia, Q, A difficult problem for genetic algorithms, 1996. Available from http://solon.cma.univie.ac.at/neum/glopt/xia.txt"
r191  "Biegler, L T, Grossmann, I E, and Westerberg, A W, Systematic Methods of Chemical Process Design. Prentice Hall, Upper Saddle River, New Jersey, 1997."
r192  "Sandgren, E, Nonlinear Integer and Discrete Programming in Mechanical Design Optimization. Journal of Mechanical Design, Trans. ASME 112 (1990), 223-229."
r193  "Beck, J V, and Arnold, K J, Parameter Estimation in Engineering and Science. Wiley, New York, 1977."
r194  "Tawarmalani, M, and Ahmed, S, Analysis of a machining process, 1997. Project Report on Design of Experiments"
r195  "Shectman, J P, and Sahinidis, N, A finite algorithm for global minimization of separable concave programs. Journal of Global Optimization 12 (1998), 1--36."
r196  "Shectman, J P, Finite Algorithms for Global Optimization of Concave Programs and General Quadratic Programs, 1999. PhD thesis, Department of Mechanical and Industrial Engineering, University of Illinois, Urbana Champagne"
r198  "Falk, J E, and Polocsay, S W, Image space analysis of generalized fractional programs. Journal of Global Optimization 4 (1994), 63-88."
r199  "Konno, H, Kuno, T, and Yajima, Y, Global optimization of a generalized convex multiplicative function. Journal of Global Optimization 4 (1994), 47-62."
r200  "Schaible, S, and Sodini, C, Finite algorithm for generalized linear multiplicative programming. Journal of Optimization Theory and Applications 87 (1995), 441-455."
r201  "Tsai, L -, and Morgan, A P, Solving the kinematics of the most general six- and five-degree-of-freedom manipulators by continuation methods. ASME J. Mech. Transm. Automa. Des. 107 (1985), 189-200."
r202  "ARKI Consulting, ARKI Consulting Client Models."
r203  "Stinstra, E, den Hertog, D, Stehouwer, H P, and Vestjens, A, Constrained Maximin Designs for Computer Experiments. Technometrics (under revision) (2002)."
r204  "Pinter, J D, LGO - A Model Development System for Continuous Global Optimization. User's Guide. (Revised edition). Pinter Consulting Services, Halifax, NS Canada, 2003."
r205  "Mathematica, MathOptimizer - An Advanced Modeling and Optimization System for Mathematica Users. http://www.wolfram.com/products/applications/mathoptimizer/"
r206  "Pinter, J D, Global Optimization in Action. Kluwer Acadameic Publishers, Dordrecht/Boston/London, 1996."
r207  "Pinter, J D, Computational Global Optimization in Nonlinear Systems. Lionheart Publishing, Atlanta, GA, 2001."
r208  "Greenberg, B, Lasdon, L S, and Plummer, J, Using Global Optimization to Estimate Population Class Sizes. Tech. rep., McComb School of Business, University of Texas, Austin, TX, 2003."
r209  "Westerlund, T, and Lundqvist K., Alpha-ECP, Version 5.01 An Interactive MINLP-Solver Based on the Extended Cutting Plane Method, Report 01-178-A. Tech. rep., Process Design Laboratory at Abo University, 2001."
r210  "GAMS Software GmbH, GAMS Software Client Models."
r211  "GAMS Development, GAMS Development Client Models."
r212  "Drud, A, Missing bounds in models ex8_2_*.gms, Private Communications, 2004."
r213  "Drud, A, Missing bounds and replacement of common multiplicative sub-expression exp(data-b(i)) in models ex8_2_*.gms, Private Communications, 2004."
r214  "Edgar, T F, Himmelblau, D M, and Lasdon, L S, Optimization of Chemical Processes. McGraw Hill, Boston, 2001."
r215  "Binous, H, Chemical Engineering Application Models. (Contributed models)"
/
$onempty
set cr(r,r) cross references /
r5.(r6)
r8.(r9)
r16.(r17)
r19.(r20)
r26.(r27)
r34.(r35)
r40.(r41)
r42.(r43)
r72.(r73)
r96.(r97)
r106.(r107)
r163.(r147,r154,r155,r156,r157,r158,r159,r160,r161,r162)
r164.(r149,r152)
r165.(r145,r146)
/
$offempty
set ca(a) credit authors /
"Handbook of Test Problems"
/
set af(a,r) first author     /
"Abate, M".(r76)
"ACC".(r16)
"Ackermann, J".(r21)
"Adhya, N".(r111)
"Adjiman, C S".(r12)
"Aggarwal, A".(r84)
"Al-Khayyal, F A".(r179)
"Anandalingam, G".(r47)
"Anitescu, M".(r104)
"ARKI Consulting".(r202)
"Ascher, U M".(r94)
"Ashrafi, N".(r188)
"Averick, B M".(r88)
"Avriel, M".(r28)
"Bard, J F".(r37,r39)
"Barmish, B R".(r75)
"Beck, J V".(r193)
"Ben-Sadd, S".(r15)
"Ben-Tal, A".(r25)
"Berman, O".(r49)
"Berna, T".(r123)
"Betts, J".(r101)
"Biegler, L T".(r191)
"Binous, H".(r215)
"Blitzer, C".(r141)
"Borland".(r125)
"Box, G E P".(r99)
"Bracken, J".(r163,r147,r154,r155,r156,r157,r158,r160,r161,r162,r159)
"Brooke, A".(r150,r122)
"Bryson, A E".(r95,r109)
"Bulirsch, R".(r96,r97)
"Bullard, L G".(r13)
"Candler, W".(r48)
"Capriz, G".(r107)
"Carlson, R C".(r121)
"Castillo, J".(r70)
"Cesari, L".(r98)
"Chenery, H B".(r153)
"Clark, P A".(r29,r32)
"Coello Coello, C A".(r119)
"Colville, A R".(r20)
"Condon, T".(r116)
"Csendes, T".(r77)
"Dahl, H".(r148)
"de Gaston, R".(r58)
"Deb, K".(r118)
"Dembo, R S".(r65)
"Dixon, L".(r6,r9)
"Dolan, E D".(r110)
"Drud, A".(r212,r213)
"Drud, A S".(r151)
"Edgar, T F".(r214)
"Esposito, W R".(r74,r86)
"Fair, R C".(r135)
"Falk, J E".(r66,r182,r198)
"Fasano, A".(r106)
"Ferraris, G B".(r14)
"Floudas, C A".(r124,r44,r1,r34,r42,r43,r72,r175)
"Friedman, A".(r91)
"GAMS Development".(r211)
"GAMS Software GmbH".(r210)
"Gay, D M".(r105)
"Gill, P E".(r120)
"Glowinski, R".(r90)
"Goldstein, A".(r7)
"Graham, R L".(r100)
"Green, K".(r30)
"Greenberg, B".(r208)
"Grossmann, I E".(r40,r80)
"Harding, S T".(r81)
"Harker, P T".(r129)
"Haverly, C A".(r83)
"Heidemann, R".(r57)
"Hesse, R".(r23)
"Himmelblau, D M".(r164,r149,r152)
"Hock, W".(r26,r27)
"Hua, J".(r67)
"Kalantari, B".(r178)
"Kearfott, R".(r60)
"Kendrick, D".(r136,r143)
"Kim, I".(r82)
"Kim, Y S".(r186)
"Kocis, G R".(r45)
"Konno, H".(r180,r199)
"Kubicek, M".(r54)
"Kuhn, H W".(r19)
"Kutcher, G P".(r127)
"Le-Si, V".(r128)
"Lewis, J".(r113)
"Li, H".(r184)
"Liebman, J".(r170)
"Liu, Y H".(r31)
"Magnussen, T".(r62)
"Mangasarian, O L".(r126)
"Manne, A S".(r139,r132,r140)
"Manousiouthakis, V".(r63)
"Maranas, C D".(r10,r64)
"Maria, G".(r89)
"Marin, R".(r189)
"Mathematica".(r205)
"McDonald, C M".(r52,r53,r55,r56,r61)
"Meintjes, K".(r59)
"Michelsen, M L".(r71)
"Mitra, P".(r114,r115)
"Moore, R E".(r3,r73)
"Morari, M".(r112)
"Morris, J R".(r92)
"Murtagh, B A".(r138,r22)
"Norton, R D".(r142)
"Pindyck, R S".(r144)
"Pinter, J D".(r204,r206,r207)
"Ramsey, F P".(r137)
"Ratschek, H".(r69)
"Reklaitis, G".(r51)
"Rod, V".(r79)
"Rosenbrock, H H".(r131)
"Rothschild, B J".(r102)
"Ryoo, H S".(r24)
"Saff, E B".(r93)
"Sahinidis, N".(r168,r183)
"Sandgren, E".(r192)
"Schaible, S".(r200)
"Schweiger, C A".(r85)
"Shectman, J P".(r195,r196)
"Shimizu, K".(r33,r68)
"Shin, D K".(r185)
"SIAM".(r8)
"Siddall, J N".(r117)
"Sideris, A".(r17)
"Smith, J".(r50)
"Soland, R M".(r11)
"Stephanopoulos, G".(r173)
"Stinstra, E".(r203)
"Stoecker, W F".(r169)
"Swaney, R E".(r171)
"Tawarmalani, M".(r167,r194)
"Thakur, L S".(r187)
"Thoai, N V".(r181)
"Tjoa, I B".(r78,r87)
"Tsai, L -".(r201)
"Tuy, H".(r38,r177)
"University of Cagliari".(r5)
"Vanderbei, R".(r103)
"Vicino, A".(r36)
"Visweswaran, V".(r35,r41,r176)
"von Stryk, O".(r108)
"Wall, T W".(r134)
"Westerberg, A W".(r172)
"Westerlund, T".(r209)
"Wilkinson, J H".(r4)
"Wingo, D".(r2)
"Wood, A J".(r165,r146,r145)
"Wright, M H".(r130)
"Xia, Q".(r190)
"Yezza, A".(r18)
"Yuan, X".(r46,r174)
"Zenios, S A".(r133)
/
set ar(a,r) author reference mapping /
"Abate, M".(r76)
"ACC".(r16)
"Ackermann, J".(r21)
"Adhya, N".(r111)
"Adjiman, C S".(r1,r12)
"Aggarwal, A".(r84)
"Ahmed, S".(r194)
"Aiyoshi, E".(r33)
"Al-Khayyal, F A".(r179)
"Anandalingam, G".(r47)
"Anitescu, M".(r104)
"ARKI Consulting".(r202)
"Arnold, K J".(r193)
"Ascher, U M".(r94)
"Ashrafi, N".(r49,r188)
"Averick, B M".(r88)
"Avriel, M".(r28)
"Bard, J F".(r37,r39,r68)
"Barmish, B R".(r75,r76)
"Beck, J V".(r193)
"Beltramo, M A".(r139)
"Ben-Sadd, S".(r15)
"Ben-Tal, A".(r25)
"Berman, O".(r49,r188)
"Berna, T".(r123)
"Betts, J".(r101)
"Biegler, L T".(r13,r78,r87,r191)
"Binous, H".(r215)
"Blitzer, C".(r141)
"Bondarenko, A S".(r102)
"Borland".(r125)
"Box, G E P".(r99)
"Bracken, J".(r163,r147,r154,r155,r156,r157,r158,r160,r161,r162,r159)
"Brennecke, J".(r67)
"Brooke, A".(r150,r122)
"Bryson, A E".(r95,r109)
"Bulirsch, R".(r96,r97)
"Bullard, L G".(r13)
"Candler, W".(r48)
"Capriz, G".(r107)
"Carlson, R C".(r121)
"Carter, R G".(r88)
"Castillo, J".(r70)
"Cesari, L".(r98)
"Chenery, H B".(r153)
"Chou, C".(r184)
"Cimatti, G".(r107)
"Ciric, A R".(r42,r43,r175)
"Clark, P A".(r29,r32)
"Coello Coello, C A".(r119)
"Colville, A R".(r20)
"Condon, T".(r116)
"Csendes, T".(r77)
"Dahl, H".(r148,r116)
"Dallwig, S".(r12)
"de Gaston, R".(r58)
"Deaven, D M".(r92)
"Deb, K".(r118)
"Dembo, R S".(r65)
"den Hertog, D".(r203)
"Devarajan, S".(r116)
"Dixon, L".(r6,r9)
"Dolan, E D".(r110)
"Domenech, S".(r174)
"Drud, A".(r212,r213)
"Drud, A S".(r151,r150,r133)
"Edgar, T F".(r214,r82)
"Eiger, G".(r25)
"Eldersveld, S".(r101)
"Erjavec, J".(r99)
"Esposito, W R".(r1,r74,r86)
"Fair, R C".(r135)
"Falk, J E".(r39,r66,r179,r182,r198)
"Fasano, A".(r106)
"Ferraris, G B".(r14)
"Floudas, C A".(r124,r44,r84,r1,r10,r12,r34,r41,r42,r43,r53,r55,r56,r61,r64,r72,r74,r81,r85,r86,r175,r176)
"Fredenslund, A".(r62)
"Friedman, A".(r91)
"GAMS Development".(r211)
"GAMS Software GmbH".(r210)
"Gay, D M".(r105)
"Gershovitz, V".(r25)
"Gill, P E".(r120)
"Glowinski, R".(r90)
"Goldstein, A".(r7)
"Goyal, M".(r118)
"Graham, R L".(r100)
"Green, K".(r30)
"Greenberg, B".(r208)
"Greening, D".(r134)
"Griffin, O H".(r185)
"Grossmann, I E".(r45,r112,r40,r70,r80,r168,r191)
"Gumus, Z H".(r1)
"Gurdal, Z".(r185)
"Hancil, V".(r79)
"Handbook of Test Problems".(r1)
"Hansen, E".(r73)
"Harding, S T".(r1,r81)
"Harker, P T".(r129)
"Hart, S M".(r31)
"Haverly, C A".(r83)
"Heidemann, R".(r57)
"Hesse, R".(r23)
"Himmelblau, D M".(r214,r164,r149,r152)
"Hlavacek, V".(r54)
"Ho, K M".(r92)
"Ho, Y".(r109)
"Hock, W".(r26,r27)
"Hofmann, H".(r54)
"Hua, J".(r67)
"Huffman, W".(r101)
"Hunter, W G".(r99)
"Ishizuka, Y".(r68)
"Kaesbauer, D".(r21)
"Kalantari, B".(r178)
"Kasnagoklu, H".(r128)
"Kearfott, R".(r60)
"Kendrick, D".(r122,r136,r143)
"Kim, I".(r82)
"Kim, Y S".(r186)
"Klepeis, J L".(r1)
"Kocis, G R".(r45)
"Konno, H".(r180,r199)
"Kubicek, M".(r54)
"Kuhn, H W".(r19)
"Kuijlaars, A".(r93)
"Kuno, T".(r180,r199)
"Kutcher, G P".(r127)
"Lasdon, L S".(r214,r170,r208)
"Le-Si, V".(r128)
"Leclerc, A".(r73)
"Lewis, J".(r113)
"Li, H".(r184)
"Liebman, J".(r170)
"Liebman, M J".(r82)
"Liu, J".(r66)
"Liu, Y H".(r31)
"Locke, M".(r123)
"Luks, K".(r30)
"Lundqvist K.".(r209)
"MacGregor, J F".(r99)
"Magnussen, T".(r62)
"Mandhane, J".(r57)
"Mangasarian, O L".(r126)
"Manne, A S".(r139,r132,r140)
"Manousiouthakis, V".(r63)
"Maranas, C D".(r10,r64)
"Maria, G".(r89)
"Marin, R".(r189)
"Mathematica".(r205)
"Mattheij, R M M".(r94)
"McCormick, G P".(r163,r147,r154,r155,r156,r157,r158,r160,r161,r162,r159)
"McDonald, C M".(r52,r53,r55,r56,r61)
"Meeraus, A".(r150,r148,r122,r127,r141)
"Meintjes, K".(r59)
"Meyer, C A".(r1)
"Michelsen, M L".(r71)
"Migdalas, A".(r38)
"Mitra, P".(r114,r115)
"Moore, R E".(r3,r73)
"Morari, M".(r112)
"More, J J".(r88,r110)
"Morgan, A P".(r59,r201)
"Morris, J R".(r92)
"Muench, R".(r21)
"Mulvey, J".(r133)
"Murillo-Sanchez, C".(r76)
"Murray, W".(r120)
"Murtagh, B A".(r138,r22)
"Nelson, C R".(r140)
"Nemhauser, G L".(r121)
"Nerz, E".(r97)
"Neumaier, A".(r12)
"Norton, R D".(r142)
"Novoa, M".(r60)
"O'Mara, G T".(r127)
"Pardalos P M".(r72)
"Pardalos, P M".(r1,r34)
"Paules IV, G E".(r124)
"Pesch, H J".(r97)
"Pibouleau, L".(r46,r174)
"Pindyck, R S".(r144)
"Pinter, J D".(r204,r206,r207)
"Plummer, J".(r208)
"Polocsay, S W".(r198)
"Price, J".(r7)
"Primicerio, M".(r106)
"Raduchel, W J".(r153)
"Ragsdell, K".(r51)
"Ramsey, F P".(r137)
"Rasmussen, P".(r62)
"Ratschek, H".(r69)
"Ratz, D".(r77)
"Reklaitis, G".(r51)
"Robinson, S".(r113)
"Rod, V".(r79)
"Rokne, J".(r69)
"Rosen, J B".(r178)
"Rosenborg, A".(r151)
"Rosenbrock, H H".(r131)
"Rothschild, B J".(r102)
"Russell, R D".(r94)
"Ryoo, H S".(r24)
"Saff, E B".(r93)
"Safonov, M".(r58)
"Sahinidis, N".(r111,r24,r167,r168,r183,r195)
"Sanchez".(r17)
"Sandgren, E".(r192)
"Sargent, R".(r80)
"Saunders, M A".(r120,r138,r22)
"Scandizzo, P L".(r142,r128)
"Schaible, S".(r200)
"Schittkowski, K".(r26,r27)
"Schrage, L".(r170)
"Schweiger, C A".(r1,r85)
"Serban, R".(r104)
"Shah, J V".(r172)
"Sharov, A F".(r102)
"Shectman, J P".(r195,r196)
"Shimizu, K".(r33,r68)
"Shin, D K".(r185)
"SIAM".(r8)
"Siddall, J N".(r117)
"Sideris, A".(r17)
"Sinkule, J".(r54)
"Smith, J".(r50)
"So, K C".(r140)
"Sodini, C".(r200)
"Soland, R M".(r11,r182)
"Sourlas, D".(r63)
"Stadtherr, M".(r67)
"Stehouwer, H P".(r203)
"Stephanopoulos, G".(r173)
"Stinstra, E".(r203)
"Stoecker, W F".(r169)
"Stoutjesdijk, A J".(r141)
"Swaney, R E".(r171)
"Szegoe, G P".(r6)
"Tawarmalani, M".(r111,r167,r183,r194)
"Taylor, L".(r143)
"Tempo, R".(r76)
"Tendulkar, S".(r115)
"Tesi, A".(r36)
"Thai, N Q".(r177)
"Thakur, L S".(r187)
"Thieu, T V".(r177)
"Thoai, N V".(r181)
"Tjoa, I B".(r78,r87)
"Townsley, R".(r48)
"Tronconi, E".(r14)
"Tsai, L -".(r201)
"Tuy, H".(r38,r177)
"University of Cagliari".(r5)
"Vanderbei, R".(r103)
"Varbrand, P".(r38)
"Vestjens, A".(r203)
"Vicino, A".(r36)
"Visweswaran, V".(r35,r41,r176)
"von Stryk, O".(r97,r108)
"Wall, T W".(r134)
"Waren, A D".(r170)
"Westerberg, A W".(r123,r29,r32,r172,r173,r191)
"Westerlund, T".(r209)
"Weyant, J P".(r140)
"White, D J".(r47)
"Wilkinson, J H".(r4)
"Williams, A C".(r28)
"Wingo, D".(r2)
"Wollenberg, B F".(r165,r146,r145)
"Wood, A J".(r165,r146,r145)
"Woolsey, R E D".(r134)
"Wright, M H".(r130)
"Xia, Q".(r190)
"Xue, G L".(r88)
"Yajima, Y".(r199)
"Yezza, A".(r18)
"Yu, M".(r183)
"Yuan, X".(r46,r174)
"Zenios, S A".(r148,r133)
"Zhang, S".(r46,r174)
"Zhou, S".(r30)
/
