$onempty
set a authors /
"Adjiman, C S"
"Aggarwal, A"
"Ahadi-Oskui, T"
"Alperin, H"
"Ashrafi, N"
"Back, T"
"Berman, O"
"Biegler, L T"
"Brooke, A"
"Bussieck, M R"
"Castillo, I"
"Chou, C"
"Claessens, M T"
"Cziesla, F"
"Dahl, H"
"de Klerk, E"
"de Wolf, D"
"Deb, K"
"Domenech, S"
"Drud, A S"
"Duran, M A"
"Edgar, T F"
"Emetb, S"
"Esposito, W R"
"Falk, J E"
"Floudas Test Problems Modified"
"Floudas, C A"
"GAMS Dev. Client Models"
"GAMS Development"
"GAMS Software Client Models"
"GAMSLIB"
"GAMSLIB Modified"
"Goyal, M"
"Griffin, O H"
"Grossmann, I E"
"Gumus, Z H"
"Gupta, O K"
"Gurdal, Z"
"Handbook of Test Problems"
"Harding, S T"
"Harjunkoski, I"
"Himmelblau, D M"
"Hoogenboom, J E"
"Illes, T"
"Jain, V"
"Juedes, M"
"Klepeis, J L"
"Kocis, G R"
"Lasdon, L S"
"Leyffer, S"
"Li, H"
"Lundqvist K."
"MacMINLP Library"
"MacMINLP Library Modified"
"Manne, A S"
"Marin, R"
"Mavrotas, G"
"Meeraus, A"
"Meyer, C A"
"Michalek, J J"
"MINOPT Library"
"MINOPT Library Modified"
"Mittelmann, H"
"Moon, I"
"Nowak, I"
"Paradalos, P M"
"Pardalos, P M"
"Paules IV, G E"
"Petterson, F"
"Pibouleau, L"
"Porn, R"
"Quist, A J"
"Ragavan, R"
"Ravindran, A"
"Rohde, S M"
"Romeijn, E"
"Roos, K"
"Rosenborg, A"
"Sahinidis, N"
"Sandgren, E"
"Schoonen, B"
"Schweiger, C A"
"Shectman, J P"
"Shiau, C N"
"Shin, D K"
"Silver, E A"
"Skrifvars, H"
"Smeers, Y"
"Soland, R M"
"Still, C"
"Tawarmalani, M"
"Terlaky, T"
"Tin-Loi, F"
"Tsatsaronis, G"
"van Dijk, N M"
"van Geemert, R"
"Vecchietti, A"
"Vigerske, S"
"Viswanathan, J"
"Westerberg, A W"
"Westerlund, J"
"Westerlund, T"
"Wollenberg, B F"
"Wood, A J"
"Yee, T F"
"Yu, M"
"Yuan, X"
"Zamora, J"
"Zenios, S A"
"Zhang, S"
"Zwaneveld, P J"
/
set r references /
r1  "GAMS Development, GAMS Model Library."
r2  "GAMS Development, Reformulation of Models from GAMS Library."
r3  "Floudas, C A, Pardalos, P M, Adjiman, C S, Esposito, W R, Gumus, Z H, Harding, S T, Klepeis, J L, Meyer, C A, and Schweiger, C A, Handbook of Test Problems in Local and Global Optimization. Kluwer Academic Publishers, 1999."
r4  "GAMS Development, Reformulation of Models from Handbook of Test Problems in Local and Global Optimization."
r5  "Leyffer, S, MacMINLP: AMPL Collection of Mixed Integer Nonlinear Programs."
r6  "GAMS Development, Reformulation of Models from MacMINLP."
r7  "GAMS Development, GAMS Software Client Models."
r8  "GAMS Development, GAMS Development Client Models."
r9  "Vecchietti, A, Aldo Vecchietti's Model Collection."
r10  "Floudas, C A, and Schweiger, C A, MINOPT Model Library."
r11  "GAMS Development, Reformulation of Models from MINOPT Library."
r12  "Edgar, T F, Himmelblau, D M, and Lasdon, L S, Optimization of Chemical Processes. McGraw Hill, Boston, 2001."
r13  "Manne, A S, GAMS/MINOS: Three examples. Tech. rep., Department of Operations Research, Stanford University, 1986."
r14  "Duran, M A, and Grossmann, I E, An Outer-Approximation Algorithm for a Class of Mixed-Integer Nonlinear Programs. Mathematical Programming 36 (1986), 307-339."
r15  "Kocis, G R, and Grossmann, I E, Relaxation Strategy for the Structural Optimization of Process Flow Sheets. Industrial and Engineering Chemical Research 26, 9 (1987), 1869-1880."
r16  "Kocis, G R, and Grossmann, I E, Global Optimization of Nonconvex MINLP Problems in Process Synthesis. Industrial and Engineering Chemical Research 27 (1988), 1407-1421."
r17  "Kocis, G R, and Grossmann, I E, A Modeling and Decomposition Strategy for the MINLP Optimization of Process Flowsheets. Computers and Chemical Engineering 13, 7 (1989), 797-819."
r19  "Viswanathan, J, and Grossmann, I E, A Combined Penalty Function and Outer Approximation Method for MINLP Optimization. Computers and Chemical Engineering 14, 7 (1990), 769-782."
r20  "Sandgren, E, Nonlinear Integer and Discrete Programming in Mechanical Design Optimization. Journal of Mechanical Design, Trans. ASME 112 (1990), 223-229."
r21  "Aggarwal, A, and Floudas, C A, Synthesis of General Distillation Sequences: Nonsharp Separation. Computers and Chemical Engineering 14, 6 (1990), 631-653."
r22  "Zenios, S A, Ed, Financial Optimization. Cambridge University Press, New York, NY, 1993."
r23  "Dahl, H, Meeraus, A, and Zenios, S A, Some Financial Optimization Models: Risk Management. In Zenios, S A, Ed, Financial Optimization. Cambridge University Press, New York, NY, 1993."
r24  "Ragavan, R, and Rohde, S M, Eds, Computers in Engineering, Vol. III, 1985."
r25  "Wood, A J, and Wollenberg, B F, Power Generation, Operation and Control. John Wiley and Sons, 1984."
r26  "Floudas, C A, Nonlinear and Mixed Integer Optimization: Fundamentals and Applications. Oxford University Press, 1995."
r27  "Quist, A J, de Klerk, E, Roos, K, Terlaky, T, van Geemert, R, Hoogenboom, J E, and Illes, T, Finding Optimal Nuclear Reactor Core Reload Patterns Using Nonlinear Optimization and Search Heuristics. Engineering Optimization 32 (1999), 143-176."
r28  "Jain, V, and Grossmann, I E, Cyclic Scheduling of Continuous Parallel Units with Decaying Performance. American Institute of Chemical Engineers Journal 44, 7 (1998), 1623-1636."
r29  "Harjunkoski, I, Westerlund, T, Porn, R, and Skrifvars, H, Different Transformations for Solving Non-Convex Trim Loss Problems by MINLP. European Journal of Operational Research 105, 3 (1998), 594-603."
r30  "Silver, E A, and Moon, I, A Fast Heuristic for Minimizing Total Average Cycle Stock Subject to Practical Constraints. Journal of the Operational Research Society 50 (1999), 789-796."
r31  "Back, T, Ed, Proceedings of the Seventh International Conference on Genetic Algorithms, 1997."
r32  "Yee, T F, and Grossmann, I E, Simultaneous Optimization of Models for Heat Integration - Heat Exchanger Network Synthesis. Computers and Chemical Engineering 14, 10 (1990), 1165-1184."
r33  "Westerlund, T, Petterson, F, and Grossmann, I E, Optimization of Pump Configurations as a MINLP Problem. Computers and Chemical Engineering 18, 9 (1994), 845-858."
r34  "Wood, A J, and Wollenberg, B F, Example Problem 4e. In Power Generation, Operation and Control. John Wiley and Sons, 1984, pp. 85-88."
r35  "Edgar, T F, Himmelblau, D M, and Lasdon, L S, Example 13.4. In Optimization of Chemical Processes. McGraw Hill, Boston, 2001, pp. 469-478."
r36  "de Wolf, D, and Smeers, Y, The Gas Transmission Problem Solved by and Extension of the Simplex Algorithm. Management Science 46, 11 (2000), 1454-1465."
r37  "Deb, K, and Goyal, M, Optimizing Engineering Designs Using a Combined Genetic Search. In Back, T, Ed, Proceedings of the Seventh International Conference on Genetic Algorithms. 1997, pp. 521-528."
r38  "Kocis, G R, and Grossmann, I E, Computational Experience with DICOPT Solving Minlp Problems in Process Synthesis. Computers and Chemical Engineering 13, 3 (1989), 307-315."
r39  "Mittelmann, H, Model Collection."
r40  "Tin-Loi, F, Model Collection."
r41  "Brooke, A, Drud, A S, and Meeraus, A, Modeling Systems and Nonlinear Programming in a Research Environment. In Ragavan, R, and Rohde, S M, Eds, Computers in Engineering, Vol. III. ACME, 1985."
r42  "Drud, A S, and Rosenborg, A, Dimensioning Water Distribution Networks. Masters thesis, Institute of Mathematical Statistics and Operations Research, Technical University of Denmark, 1973. (in Danish)"
r43  "Zamora, J, and Grossmann, I E, A Global MINLP Optimization Algorithm for the Synthesis of Heat Exchanger Networks with No Stream Splits. Computers and Chemical Engineering 22, 3 (1998), 367-384."
r44  "Yuan, X, Zhang, S, and Pibouleau, L, A Mixed-Integer Nonlinear-Programming Method for Process Design. RAIRO - Recherche Operationnelle-Operations Research 22 (1988), 331-346."
r45  "Porn, R, Harjunkoski, I, and Westerlund, T, Convexification of Different Classes of Non-Convex MINLP Problems. Computers and Chemical Engineering 23 (1999), 439-448."
r46  "Berman, O, and Ashrafi, N, Optimization Models for Reliability of Modular Software Systems. IEEE Transactions on Software Engineering 19, 11 (1993), 1119-1123."
r47  "Floudas, C A, and Paules IV, G E, A Mixed-Integer Nonlinear Programming Formulation for the Synthesis of Heat Integrated Distillation Sequence. Computers and Chemical Engineering 12, 6 (1988), 531-546."
r48  "Bussieck, M R, Optimal Lines in Public Rail Transport. PhD thesis, TU Braunschweig, 1998."
r49  "Claessens, M T, van Dijk, N M, and Zwaneveld, P J, Cost Optimal Allocation of Rail Passenger Lines. European Journal Operation Research 110, 3 (1998), 474-489."
r50  "Schoonen, B, Bram Schoonen's Model Collection."
r51  "Pardalos, P M, and Romeijn, E, Eds, Handbook of Global Optimization - Volume 2: Heuristic Approaches. Kluwer Academic Publishers, 2001."
r52  "Tawarmalani, M, and Sahinidis, N, Exact Algorithms for Global Optimization of Mixed-Integer Nonlinear Programs. In Pardalos, P M, and Romeijn, E, Eds, Handbook of Global Optimization - Volume 2: Heuristic Approaches. Kluwer Academic Publishers, 2001."
r53  "Gupta, O K, and Ravindran, A, Branch and Bound Experiments in Convex Nonlinear Integer Programming. Management Science 13 (1985), 1533-1546."
r54  "Tawarmalani, M, and Sahinidis, N, Convexification and Global Optimization in Continuous and Mixed-Integer Nonlinear Programming: Theory, Algorithms, Software, and Applications. Kluwer, 2002."
r55  "Shectman, J P, Finite Algorithms for Global Optimization of Concave Programs and General Quadratic Programs, 1999. PhD thesis, Department of Mechanical and Industrial Engineering, University of Illinois, Urbana Champagne"
r56  "Yuan, X, Zhang, S, Pibouleau, L, and Domenech, S, Une methode d'optimisation non lineaire en variables mixtes pour la conception de procedes. Recherche Operataionnelle/Operations Research 22 (1988), 331-346."
r57  "Falk, J E, and Soland, R M, An algorithm for separable nonconvex programming problems. Management Science 15 (1969), 550-569."
r58  "Ashrafi, N, and Berman, O, Optimization models for selection of programs, considering cost and reliability. IEEE Trans. Reliab.  41 (1992), 281-287."
r59  "Marin, R, Points of location on a fixture, 1998. Personal Communication"
r60  "Sahinidis, N, Tawarmalani, M, and Yu, M, Design of alternative refrigerants via global optimization, 2002. (in preparation)"
r61  "Biegler, L T, Grossmann, I E, and Westerberg, A W, Systematic Methods of Chemical Process Design. Prentice Hall, Upper Saddle River, New Jersey, 1997."
r62  "Li, H, and Chou, C, A global approach for nonlinear mixed discrete programming in design optimization. Engineering Optimization 22 (1994), 109-122."
r63  "Shin, D K, Gurdal, Z, and Griffin, O H, A penalty approach for nonlinear optimization with discrete design variables. Engineering Optimization 16 (1990), 29--42."
r64  "Westerlund, T, and Lundqvist K., Alpha-ECP, Version 5.01 An Interactive MINLP-Solver Based on the Extended Cutting Plane Method, Report 01-178-A. Tech. rep., Process Design Laboratory at Abo University, 2001."
r65  "Floudas, C A, and Paradalos, P M, Encyclopedia of Optimization. Kluwer Academic Press, 2001."
r66  "Still, C, and Westerlund, T, Extended Cutting Plane Algorithm. In Encyclopedia of Optimization. Kluwer Academic Press, 2001."
r67  "Ahadi-Oskui, T, Alperin, H, Nowak, I, Cziesla, F, and Tsatsaronis, G, A Relaxation-Based Heuristic for the Design of Cost-Effective Energy Conversion Systems. Energy 31 (2006), 1346-1357."
r68  "Castillo, I, Westerlund, J, Emetb, S, and Westerlund, T, Optimization of block layout design problems with unequal areas: A comparison of MILP and MINLP optimization methods. Computers and Chemical Engineering 30 (2005), 54-769."
r69  "Mavrotas, G, Generation of efficient solutions in Multiobjective Mathematical Programming problems using GAMS. Tech. rep., School of Chemical Engineering, National Technical University of Athens, 2006."
r70  "Juedes, M, Vigerske, S, and Tsatsaronis, G, Optimization of the Design and Partial-Load Operation of Power Plants Using Mixed-Integer Nonlinear Programming. In Kallrath, J, and Pardalos, P, Eds, Optimization in the Energy Industry. Springer, 2008."
r71  "Shiau, C N, and Michalek, J J, Global Optimization of Plug-In Hybrid Vehicle Design and Allocation to Minimize Life Cycle Greenhouse Gas Emissions. ASME Journal of Mechanical Design 133, 8 (2011). doi: <a href=http://dx.doi.org/10.1115/1.4004538>10.1115/1"
/
set r2(r) second part of references /
r71  ".4004538</a>"
/
set cr(r,r) cross references /
r12.(r35)
r22.(r23)
r24.(r41)
r25.(r34)
r31.(r37)
r51.(r52)
r65.(r66)
/
set ca(a) credit authors /
"Floudas Test Problems Modified"
"GAMS Dev. Client Models"
"GAMS Software Client Models"
"GAMSLIB"
"GAMSLIB Modified"
"Handbook of Test Problems"
"MacMINLP Library"
"MacMINLP Library Modified"
"MINOPT Library"
"MINOPT Library Modified"
/
set af(a,r) first author     /
"Aggarwal, A".(r21)
"Ahadi-Oskui, T".(r67)
"Ashrafi, N".(r58)
"Back, T".(r31)
"Berman, O".(r46)
"Biegler, L T".(r61)
"Brooke, A".(r41)
"Bussieck, M R".(r48)
"Castillo, I".(r68)
"Claessens, M T".(r49)
"Dahl, H".(r23)
"de Wolf, D".(r36)
"Deb, K".(r37)
"Drud, A S".(r42)
"Duran, M A".(r14)
"Edgar, T F".(r12,r35)
"Falk, J E".(r57)
"Floudas, C A".(r47,r26,r10,r3,r65)
"GAMS Development".(r11,r8,r7,r6,r2,r1,r4)
"Gupta, O K".(r53)
"Harjunkoski, I".(r29)
"Jain, V".(r28)
"Juedes, M".(r70)
"Kocis, G R".(r38,r17,r16,r15)
"Leyffer, S".(r5)
"Li, H".(r62)
"Manne, A S".(r13)
"Marin, R".(r59)
"Mavrotas, G".(r69)
"Mittelmann, H".(r39)
"Pardalos, P M".(r51)
"Porn, R".(r45)
"Quist, A J".(r27)
"Ragavan, R".(r24)
"Sahinidis, N".(r60)
"Sandgren, E".(r20)
"Schoonen, B".(r50)
"Shectman, J P".(r55)
"Shiau, C N".(r71)
"Shin, D K".(r63)
"Silver, E A".(r30)
"Still, C".(r66)
"Tawarmalani, M".(r52,r54)
"Tin-Loi, F".(r40)
"Vecchietti, A".(r9)
"Viswanathan, J".(r19)
"Westerlund, T".(r33,r64)
"Wood, A J".(r25,r34)
"Yee, T F".(r32)
"Yuan, X".(r44,r56)
"Zamora, J".(r43)
"Zenios, S A".(r22)
/
set ar(a,r) author reference mapping /
"Adjiman, C S".(r3)
"Aggarwal, A".(r21)
"Ahadi-Oskui, T".(r67)
"Alperin, H".(r67)
"Ashrafi, N".(r46,r58)
"Back, T".(r31)
"Berman, O".(r46,r58)
"Biegler, L T".(r61)
"Brooke, A".(r41)
"Bussieck, M R".(r48)
"Castillo, I".(r68)
"Chou, C".(r62)
"Claessens, M T".(r49)
"Cziesla, F".(r67)
"Dahl, H".(r23)
"de Klerk, E".(r27)
"de Wolf, D".(r36)
"Deb, K".(r37)
"Domenech, S".(r56)
"Drud, A S".(r42,r41)
"Duran, M A".(r14)
"Edgar, T F".(r12,r35)
"Emetb, S".(r68)
"Esposito, W R".(r3)
"Falk, J E".(r57)
"Floudas Test Problems Modified".(r4)
"Floudas, C A".(r47,r26,r21,r10,r3,r65)
"GAMS Dev. Client Models".(r8)
"GAMS Development".(r11,r8,r7,r6,r2,r1,r4)
"GAMS Software Client Models".(r7)
"GAMSLIB".(r1)
"GAMSLIB Modified".(r2)
"Goyal, M".(r37)
"Griffin, O H".(r63)
"Grossmann, I E".(r43,r38,r33,r32,r28,r19,r17,r16,r15,r14,r61)
"Gumus, Z H".(r3)
"Gupta, O K".(r53)
"Gurdal, Z".(r63)
"Handbook of Test Problems".(r3)
"Harding, S T".(r3)
"Harjunkoski, I".(r45,r29)
"Himmelblau, D M".(r12,r35)
"Hoogenboom, J E".(r27)
"Illes, T".(r27)
"Jain, V".(r28)
"Juedes, M".(r70)
"Klepeis, J L".(r3)
"Kocis, G R".(r38,r17,r16,r15)
"Lasdon, L S".(r12,r35)
"Leyffer, S".(r5)
"Li, H".(r62)
"Lundqvist K.".(r64)
"MacMINLP Library".(r5)
"MacMINLP Library Modified".(r6)
"Manne, A S".(r13)
"Marin, R".(r59)
"Mavrotas, G".(r69)
"Meeraus, A".(r41,r23)
"Meyer, C A".(r3)
"Michalek, J J".(r71)
"MINOPT Library".(r10)
"MINOPT Library Modified".(r11)
"Mittelmann, H".(r39)
"Moon, I".(r30)
"Nowak, I".(r67)
"Paradalos, P M".(r65)
"Pardalos, P M".(r3,r51)
"Paules IV, G E".(r47)
"Petterson, F".(r33)
"Pibouleau, L".(r44,r56)
"Porn, R".(r45,r29)
"Quist, A J".(r27)
"Ragavan, R".(r24)
"Ravindran, A".(r53)
"Rohde, S M".(r24)
"Romeijn, E".(r51)
"Roos, K".(r27)
"Rosenborg, A".(r42)
"Sahinidis, N".(r52,r54,r60)
"Sandgren, E".(r20)
"Schoonen, B".(r50)
"Schweiger, C A".(r10,r3)
"Shectman, J P".(r55)
"Shiau, C N".(r71)
"Shin, D K".(r63)
"Silver, E A".(r30)
"Skrifvars, H".(r29)
"Smeers, Y".(r36)
"Soland, R M".(r57)
"Still, C".(r66)
"Tawarmalani, M".(r52,r54,r60)
"Terlaky, T".(r27)
"Tin-Loi, F".(r40)
"Tsatsaronis, G".(r67,r70)
"van Dijk, N M".(r49)
"van Geemert, R".(r27)
"Vecchietti, A".(r9)
"Vigerske, S".(r70)
"Viswanathan, J".(r19)
"Westerberg, A W".(r61)
"Westerlund, J".(r68)
"Westerlund, T".(r45,r33,r29,r64,r66,r68)
"Wollenberg, B F".(r25,r34)
"Wood, A J".(r25,r34)
"Yee, T F".(r32)
"Yu, M".(r60)
"Yuan, X".(r44,r56)
"Zamora, J".(r43)
"Zenios, S A".(r22,r23)
"Zhang, S".(r44,r56)
"Zwaneveld, P J".(r49)
/
